class AppLocalizations {
  static final AppLocalizations _instance = AppLocalizations._internal();
  factory AppLocalizations() => _instance;
  AppLocalizations._internal();

  // ════════════════════════════════════════════════════════════════
  //  FRANÇAIS
  // ════════════════════════════════════════════════════════════════
  static const Map<String, String> _fr = {
    'login_title': 'Connexion',
    'signup_title': 'S\'inscrire',
    'email': 'Email',
    'password': 'Mot de passe',
    'email_required': 'Veuillez entrer votre email',
    'password_required': 'Veuillez entrer votre mot de passe',
    'invalid_email': 'Veuillez entrer un email valide',
    'logout': 'Déconnexion',
    'confirm_logout': 'Êtes-vous sûr de vouloir vous déconnecter ?',
    'login': 'Se connecter',
    'logging_in': 'Connexion en cours...',
    'continue_google': 'Continuer avec Google',
    'continue_guest': 'Continuer comme visiteur',
    'no_account': 'Pas de compte ?',
    'already_account': 'Déjà un compte ?',
    'forgot_password': 'Mot de passe oublié ?',
    'remember_me': 'Se souvenir de moi',
    'create_account': 'Créer un compte',
    'confirm_password': 'Confirmer le mot de passe',
    'confirm_password_required': 'Veuillez confirmer votre mot de passe',
    'passwords_not_match': 'Les mots de passe ne correspondent pas',
    'password_min_length': 'Au moins 8 caractères',
    'password_uppercase': 'Au moins une lettre majuscule',
    'password_lowercase': 'Au moins une lettre minuscule',
    'password_requirements': 'Le mot de passe ne respecte pas les conditions',
    'password_must_contain': 'Le mot de passe doit contenir :',
    'profile_complete_later': 'Les autres informations seront à compléter dans votre profil.',
    'agree_terms': 'J\'accepte les conditions générales d\'utilisation',
    'payment_paypal_terms_required': 'Vous devez accepter les conditions d\'utilisation',
    'payment_no_methods_title': 'Aucun moyen de paiement',
    'payment_no_methods_subtitle': 'Ajoutez une carte bancaire ou un compte PayPal',
    'signup_success': 'Compte créé avec succès !',
    'verification_email_sent': 'Un email de vérification a été envoyé à :',
    'verify_before_login': 'Veuillez vérifier votre boîte de réception et cliquer sur le lien avant de vous connecter.',
    'understand': 'OK, j\'ai compris',
    'signing_up': 'Inscription en cours...',
    'account_deactivated_error': 'Ce compte a été désactivé et sera supprimé dans 30 jours.',

    // ── Termes et Conditions ──────────────────────────────────────
    'terms_title': 'Termes et Conditions d\'Utilisation',
    'terms_description': 'Veuillez lire attentivement ces termes et conditions avant d\'utiliser notre application Winzy.',
    'terms_last_updated': 'Dernière mise à jour : 18 février 2026',

    'terms_section_1_title': '1. Acceptation des Conditions',
    'terms_section_1_content': 'En accédant et en utilisant l\'application Winzy, vous acceptez d\'être lié par ces conditions générales d\'utilisation. Si vous n\'acceptez pas ces conditions, veuillez ne pas utiliser notre service. L\'utilisation continue de l\'application après toute modification constitue votre acceptation des nouvelles conditions.',

    'terms_section_2_title': '2. Utilisation du Service',
    'terms_section_2_content': 'Winzy est une plateforme de commerce électronique qui vous permet d\'acheter et de vendre des produits. Vous vous engagez à utiliser le service de manière légale et éthique, à ne pas publier de contenu frauduleux ou trompeur, à respecter les droits des autres utilisateurs et à ne pas tenter de compromettre la sécurité de la plateforme.',

    'terms_section_3_title': '3. Confidentialité et Données Personnelles',
    'terms_section_3_content': 'Nous collectons et traitons vos données personnelles conformément à notre politique de confidentialité. Vos informations sont utilisées uniquement pour améliorer votre expérience sur la plateforme et traiter vos commandes. Nous ne vendons jamais vos données à des tiers. Vous pouvez demander la suppression de vos données à tout moment.',

    'terms_section_4_title': '4. Paiements et Remboursements',
    'terms_section_4_content': 'Tous les paiements sont traités de manière sécurisée. Les prix affichés incluent toutes les taxes applicables. En cas de litige concernant une commande, notre équipe de support est disponible pour vous aider. Les remboursements sont traités dans un délai de 5 à 10 jours ouvrables selon votre mode de paiement.',

    'terms_section_5_title': '5. Limitation de Responsabilité',
    'terms_section_5_content': 'Winzy s\'efforce de garantir la disponibilité et la fiabilité du service, mais ne peut être tenu responsable des interruptions temporaires de service, des erreurs de contenu, des dommages indirects résultant de l\'utilisation du service, ni des actions des vendeurs tiers sur la plateforme.',
    'terms_conditions': 'Conditions Générales d\'Utilisation',

    'close': 'Fermer',
    'i_agree': 'J\'accepte',


    'forgot_password_title': 'MOT DE PASSE OUBLIÉ',
    'forgot_password_desc': 'Entrez votre adresse email pour recevoir\nun lien de réinitialisation',
    'send_link': 'Envoyer le lien',
    'sending': 'Envoi en cours...',
    'back_to': 'Retourner à la',
    'login_page': 'page de connexion',
    'email_sent': 'Email envoyé !',
    'reset_link_sent': 'Un lien de réinitialisation a été envoyé à',
    'check_inbox_reset': 'Vérifiez votre boîte de réception et cliquez sur le lien pour réinitialiser votre mot de passe',
    'continue': 'Continuer',
    'home': 'Accueil',
    'cart': 'Panier',
    'history': 'Historique',
    'profile': 'Profil',
    'settings': 'Paramètres',
    'personal_info': 'Informations personnelles',
    'addresses': 'Adresses',
    'payment_methods': 'Méthodes de paiement',
    'notification_settings': 'Paramètres de notification',
    'security': 'Sécurité',
    'language': 'Langue',
    'help': 'Aide',
    'orders': 'Commandes',
    'favorites': 'Favoris',
    'points': 'Points',
    'change_password': 'Changer le mot de passe',
    'current_password': 'Mot de passe actuel',
    'new_password': 'Nouveau mot de passe',
    'confirm_password_field': 'Confirmer le mot de passe',
    'two_factor_auth': 'Authentification à deux facteurs',
    'biometric_auth': 'Authentification biométrique',
    'active_sessions': 'Sessions actives',
    'payment': 'Paiement',
    'order_summary': 'Résumé de la commande',
    'delivery_address': 'Adresse de livraison',
    'payment_method': 'Méthode de paiement',
    'subtotal': 'Sous-total',
    'shipping': 'Livraison',
    'discount': 'Réduction',
    'total': 'Total',
    'pay': 'Payer',
    'credit_card': 'Carte bancaire',
    'paypal': 'PayPal',
    'apple_pay': 'Apple Pay',
    'session_warning': 'Avertissement de session',
    'inactivity_warning': 'Vous allez être déconnecté en raison de l\'inactivité',
    'stay_logged_in': 'Rester connecté',
    'session_expired': 'Votre session a expiré',
    'inactivity_detected': 'Inactivité détectée',
    'remaining_time': 'Temps restant',
    'success': 'Succès',
    'error': 'Erreur',
    'loading': 'Chargement...',
    'no_data': 'Aucune donnée',
    'save': 'Enregistrer',
    'edit': 'Modifier',
    'delete': 'Supprimer',
    'confirm': 'Confirmer',
    'cancel': 'Annuler',
    'back': 'Retour',
    'ok': 'OK',
    'add': 'Ajouter',
    'by_default': 'Par défaut',

    // ── Panier ────────────────────────────────────────────────────
    'cart_title': 'Panier',
    'select_all': 'Tout',
    'summary': 'Résumé',
    'article': 'article',
    'articles': 'articles',
    'reductions': 'Réductions',
    'estimated_total': 'Total estimé',
    'checkout': 'Commander',
    'empty_cart': 'Votre panier est vide',
    'item_removed': 'Article supprimé',
    'quantity': 'Quantité',
    'items_selected': 'articles sélectionnés',

    // ── Adresses ──────────────────────────────────────────────────
    'delivery_address_title': 'Adresse de livraison',
    'add_new_address': 'Ajouter une nouvelle adresse',
    'add_address_title': 'Ajouter une nouvelle adresse',
    'edit_address_title': 'Modifier l\'adresse',
    'default_address': 'Adresse par défaut',
    'set_as_default': 'Par défaut',
    'no_addresses': 'Aucune adresse',
    'add_first_address': 'Ajoutez votre première adresse de livraison',
    'loading_addresses': 'Chargement des adresses...',
    'delete_address': 'Supprimer l\'adresse',
    'confirm_delete_address': 'Êtes-vous sûr de vouloir supprimer cette notification ?',
    'address_saved': 'Adresse enregistrée avec succès !',
    'address_updated': 'Adresse mise à jour avec succès !',
    'address_default_updated': 'Votre adresse par défaut a été mise à jour',
    'address_default_title': 'Adresse par défaut',
    'address_load_error': 'Erreur lors du chargement des adresses',
    'new_badge': 'Nouveau !',
    'all_info_encrypted': 'Toutes vos informations sont cryptées',
    'info_encrypted_secure': 'Vos informations sont cryptées et sécurisées',
    'update_address_info': 'Mettez à jour vos informations d\'adresse',

    // ── Formulaire d'adresse ──────────────────────────────────────
    'section_contact_info': 'Informations de contact',
    'section_address_info': 'Informations d\'adresse',
    'contact_name': 'Nom du contact',
    'contact_name_required': 'Veuillez entrer un nom de contact',
    'hint_contact_name': 'Ex : Jean Dupont',
    'phone': 'Téléphone',
    'phone_required': 'Veuillez entrer un numéro de téléphone',
    'hint_phone': 'Ex : 20 123 456',
    'street': 'Rue / Adresse',
    'street_required': 'Veuillez entrer une adresse',
    'hint_street': 'Ex : 12 rue de la République',
    'complement': 'Complément d\'adresse',
    'hint_complement': 'Ex : Appartement 4B, Bâtiment C',
    'province': 'Province / État',
    'province_required': 'Veuillez entrer une province',
    'hint_province': 'Ex : Tunis',
    'city': 'Ville',
    'city_required': 'Veuillez entrer une ville',
    'hint_city': 'Ex : Tunis',
    'postal_code': 'Code postal',
    'postal_code_required': 'Veuillez entrer un code postal',
    'hint_postal_code': 'Ex : 1000',
    'country': 'Pays',
    'search_country': 'Rechercher un pays...',
    'save_address_btn': 'Enregistrer l\'adresse',
    'saving_address_btn': 'Enregistrement...',
    'update_address_btn': 'Mettre à jour l\'adresse',
    'updating_address_btn': 'Mise à jour...',
    'set_default_label': 'Définir comme adresse par défaut',
    'set_default_description': 'Cette adresse sera utilisée automatiquement lors de vos commandes',

    // ── Centre d'aide ─────────────────────────────────────────────
    'help_center_title': 'Centre d\'aide',
    'help_search_hint': 'Rechercher une aide...',
    'help_category_all': 'Tous',
    'help_empty_title': 'Aucune aide trouvée',
    'help_empty_subtitle': 'Essayez de modifier votre recherche ou de changer de catégorie',
    'help_faq_content_unavailable': 'Contenu non disponible',
    'help_faq_load_error': 'Erreur lors du chargement des FAQs',
    'help_support_fab': 'Support',
    'help_contact_title': 'Contacter le support',
    'help_chat_title': 'Chat en direct',
    'help_chat_subtitle': 'Discutez avec un agent maintenant',
    'help_chat_soon': 'Chat en direct bientôt disponible !',
    'help_phone_title': 'Téléphone',
    'help_phone_subtitle': 'Appelez-nous au +216 70 000 000',
    'help_phone_unavailable': 'Application téléphonique non disponible sur cet appareil',
    'help_email_title': 'Email',
    'help_email_subtitle': 'Envoyez-nous un email à support@winzy.com',
    'help_email_copied': 'Email copié dans le presse-papiers !',
    'help_email_fallback': 'Email : support@winzy.com',
    'help_category_commandes': 'Commandes',
    'help_category_paiement': 'Paiement',
    'help_category_compte': 'Compte',
    'help_category_livraison': 'Livraison',
    'help_category_retours': 'Retours',
    'help_category_securite': 'Sécurité',
    'help_category_application': 'Application',

    // ── Paramètres de notification ────────────────────────────────
    'notif_settings_title': 'Paramètres de notification',
    'notif_save_tooltip': 'Enregistrer les paramètres',
    'notif_saved_success': 'Paramètres enregistrés avec succès !',
    'notif_section_general': 'Notifications générales',
    'notif_push_title': 'Notifications push',
    'notif_push_subtitle': 'Recevoir des notifications sur votre appareil',
    'notif_email_title': 'Notifications par email',
    'notif_email_subtitle': 'Recevoir des notifications par email',
    'notif_section_orders': 'Commandes et livraisons',
    'notif_orders_title': 'Mises à jour de commande',
    'notif_orders_subtitle': 'Tout marquer comme lu',
    'notif_section_marketing': 'Marketing et promotions',
    'notif_promo_title': 'Offres promotionnelles',
    'notif_promo_subtitle': 'Réductions et offres spéciales',
    'notif_new_products_title': 'Nouveaux produits',
    'notif_new_products_subtitle': 'Découvrez les nouveaux arrivages',
    'notif_price_drops_title': 'Baisse de prix',
    'notif_price_drops_subtitle': 'Alertes lorsque les prix baissent',
    'notif_newsletter_title': 'Newsletter',
    'notif_newsletter_subtitle': 'Actualités et conseils hebdomadaires',
    'notif_section_account': 'Compte et sécurité',
    'notif_account_title': 'Mises à jour du compte',
    'notif_account_subtitle': 'Changements importants sur votre compte',
    'notif_security_title': 'Alertes de sécurité',
    'notif_security_subtitle': 'Activités suspectes et connexions',

    // ── Moyens de paiement ────────────────────────────────────────
    'payment_methods_title': 'Moyens de paiement',
    'payment_manage_info': 'Gérez vos cartes et préférences de paiement',
    'payment_add_fab': 'Ajouter',
    'payment_security_title': 'Sécurité des paiements',
    'payment_security_desc': 'Toutes vos transactions sont sécurisées avec le cryptage SSL. Vos informations bancaires ne sont jamais stockées sur nos serveurs.',
    'payment_pci_certified': 'Certifié PCI DSS',
    'payment_set_default': 'Définir par défaut',
    'payment_expires': 'Expire',
    'payment_add_sheet_title': 'Ajouter un moyen de paiement',
    'payment_card_option_title': 'Carte bancaire',
    'payment_card_option_subtitle': 'Ajouter une nouvelle carte Visa, Mastercard...',
    'payment_cash_option_title': 'Paiement à la livraison',
    'payment_cash_option_subtitle': 'Activer le paiement lors de la livraison',
    'payment_cash_activated': 'Paiement à la livraison activé !',
    'payment_add_card_title': 'Ajouter une carte bancaire',
    'payment_add_card_content': 'Formulaire d\'ajout de carte à implémenter avec un service de paiement.',
    'payment_edit_coming_soon': 'Modification du moyen de paiement à implémenter.',
    'payment_add_coming_soon': 'Ajout de carte à implémenter.',
    'payment_delete_title': 'Supprimer le moyen de paiement',
    'payment_delete_confirm': 'Êtes-vous sûr de vouloir supprimer ce moyen de paiement ?',
    'payment_deleted_success': 'Moyen de paiement supprimé',
    'payment_set_default_success': 'Moyen de paiement défini par défaut',
    'payment_cash_description': 'Payer en espèces ou par carte lors de la livraison',

    // ── Modifier le profil ────────────────────────────────────────
    'edit_profile_title': 'Modifier le profil',
    'edit_profile_first_name': 'Prénom',
    'edit_profile_hint_first_name': 'Ex : Jean',
    'edit_profile_last_name': 'Nom',
    'edit_profile_hint_last_name': 'Ex : Dupont',
    'edit_profile_email': 'Email',
    'edit_profile_email_readonly': 'Email non modifiable pour des raisons de sécurité',
    'edit_profile_phone': 'Téléphone',
    'edit_profile_gender': 'Genre',
    'edit_profile_saving': 'Sauvegarde...',
    'edit_profile_save_btn': 'Sauvegarder',
    'edit_profile_success': 'Profil mis à jour avec succès !',
    'edit_profile_error': 'Erreur lors de la mise à jour du profil',
    'edit_profile_notif_title': 'Profil mis à jour',
    'edit_profile_notif_body': 'Vos informations ont été enregistrées avec succès',
    'edit_profile_first_name_required': 'Veuillez entrer votre prénom',
    'edit_profile_last_name_required': 'Veuillez entrer votre nom',
    'edit_profile_phone_required': 'Veuillez entrer votre numéro de téléphone',
    'edit_profile_section_personal': 'Informations personnelles',
    'edit_profile_section_contact': 'Contact',
    'photo_change_title':    'Changer la photo de profil',
    'photo_from_gallery':    'Choisir depuis la galerie',
    'photo_from_camera':     'Prendre une photo',
    'photo_remove':          'Supprimer la photo',
    'photo_upload_success':  'Photo de profil mise à jour !',
    'photo_upload_error':    'Erreur lors de l\'upload de la photo',
    'photo_removed_success': 'Photo de profil supprimée',

    // ── Sécurité ──────────────────────────────────────────────────
    'security_title': 'Sécurité',
    'section_confidentiality': 'Confidentialité',
    'section_session': 'Session',
    'security_subtitle': 'Gérez la sécurité de votre compte',
    'security_google_account': 'Compte Google',
    'security_google_connected': 'Votre compte est connecté via Google',
    'security_google_how_to': 'Comment changer votre mot de passe ?',
    'security_google_step1': 'Allez dans votre compte Google',
    'security_google_step2': 'Cliquez sur "Sécurité"',
    'security_google_step3': 'Sous "Connexion à Google", cliquez sur "Mot de passe"',
    'security_google_step4': 'Suivez les instructions pour changer votre mot de passe',
    'security_google_warning': 'Le changement de mot de passe doit être effectué directement sur Google pour des raisons de sécurité.',
    'security_open_google': 'Ouvrir la sécurité Google',
    'security_google_dialog_title': 'Ouvrir la sécurité Google',
    'security_google_dialog_step1': '1. Copier le lien ci-dessous',
    'security_google_dialog_step2': '2. Ouvrir votre navigateur',
    'security_google_dialog_step3': '3. Coller le lien et accéder à la page',
    'security_link_copied': 'Lien copié dans le presse-papiers !',
    'security_unsupported_title': 'Méthode de connexion non supportée',
    'security_unsupported_desc': 'Votre méthode de connexion actuelle ne permet pas de changer le mot de passe depuis cette application.',
    'security_auth_section': 'Authentification',
    'security_two_factor_subtitle': 'Ajoute une couche de sécurité supplémentaire',
    'security_biometric_subtitle': 'Utilisez votre empreinte ou visage',
    'security_change_password_subtitle': 'Mettez à jour votre mot de passe',
    'security_session_section': 'Session',
    'security_auto_logout_title': 'Déconnexion automatique',
    'security_auto_logout_subtitle': 'Déconnexion après inactivité',
    'security_inactivity_delay': 'Délai d\'inactivité',
    'security_inactivity_subtitle': 'Temps avant déconnexion automatique',
    'security_active_sessions_subtitle': 'Gérez vos connexions actives',
    'security_privacy_section': 'Confidentialité',
    'security_login_notif_title': 'Notifications de connexion',
    'security_login_notif_subtitle': 'Soyez notifié des nouvelles connexions',
    'security_download_data': 'Télécharger vos données',
    'security_download_subtitle': 'Exportez vos informations personnelles',
    'security_download_preparing': 'Préparation du téléchargement...',
    'security_download_success': 'Données exportées avec succès !',
    'security_download_confirm_title': 'Télécharger vos données',
    'security_download_confirm_body': 'Voulez-vous télécharger toutes vos informations personnelles ?',
    'security_download_btn': 'Télécharger',
    'security_share_btn': 'Partager',
    'security_delete_account': 'Supprimer le compte',
    'security_delete_account_subtitle': 'Supprimez définitivement votre compte',
    'security_delete_account_confirm': 'Êtes-vous sûr de vouloir supprimer votre compte ? Cette action est irréversible et toutes vos données seront perdues.',
    'delete_account_dialog_title': 'Supprimer mon compte',
    'delete_account_dialog_subtitle': 'Votre compte sera désactivé. Vous pouvez le récupérer dans un délai de 30 jours via l’email de réactivation envoyé à votre adresse email.',
    'delete_account_reason_label': 'Pourquoi souhaitez-vous supprimer votre compte ?',
    'delete_reason_1': 'Je n\'utilise plus l\'application',
    'delete_reason_2': 'J\'ai créé un autre compte',
    'delete_reason_3': 'L\'application ne répond pas à mes besoins',
    'delete_reason_4': 'Je suis préoccupé par ma confidentialité',
    'delete_reason_5': 'Je reçois trop de notifications',
    'delete_reason_other': 'Autre (précisez)',
    'delete_other_placeholder': 'Décrivez votre raison ici...',
    'delete_confirm_instruction': 'Pour confirmer la suppression définitive de votre compte :',
    'delete_confirm_type_label': 'Tapez',
    'delete_confirm_word': 'SUPPRIMER',
    'delete_account_btn': 'Supprimer le compte',
    'account_deactivated_message1': 'Votre compte a été désactivé et sera supprimé définitivement dans 30 jours. Un email de réactivation vous a été envoyé.',
    'reactivation_email_sent': 'Email de réactivation envoyé',
    'reactivation_email_error': 'Erreur lors de l\'envoi de l\'email de réactivation',
    'account_deactivated_title': 'Compte désactivé',
    'security_auto_logout_activated': 'Déconnexion automatique activée',
    'security_auto_logout_deactivated': 'Déconnexion automatique désactivée',
    'security_delay_changed': 'Délai d\'inactivité changé à',

    // ── Layout principal ──────────────────────────────────────────
    'main_smart_market': 'Winzy',
    'main_purchase_history': 'Historique d\'achat',
    'main_my_profile': 'Mon Profil',
    'main_login_required_title': 'Connexion requise',
    'main_login_required_body': 'Vous devez être connecté pour accéder à cette fonctionnalité.',
    'main_later': 'Plus tard',
    'main_cart_summary': 'Résumé du panier',
    'main_selected_items': 'Articles sélectionnés',
    'main_start_shopping': 'Commencer mes achats',
    'main_add_to_cart': 'Ajouter des articles pour commencer vos achats',

    // ── Notifications page ────────────────────────────────────────
    'notif_page_mark_all_read': 'Tout marquer comme lu',
    'notif_page_delete_all': 'Tout supprimer',
    'notif_page_empty_title': 'Aucune notification',
    'notif_page_empty_subtitle': 'Vous n\'avez pas de notifications pour le moment',
    'notif_page_delete_confirm_title': 'Supprimer tout',
    'notif_page_delete_confirm_body': 'Êtes-vous sûr de vouloir supprimer toutes vos notifications ?',
    'notif_page_time_ago_minutes': 'Il y a {n} minute(s)',
    'notif_page_time_ago_hours': 'Il y a {n} heure(s)',
    'notif_page_time_ago_days': 'Il y a {n} jour(s)',
    'notif_page_time_ago_default': 'Il y a quelque temps',
    'notif_page_mark_error': 'Erreur lors du marquage',
    'notif_page_delete_error': 'Erreur lors de la suppression',

    // ── Sessions actives ──────────────────────────────────────────
    'session_cannot_revoke_current': 'Impossible de révoquer la session actuelle',
    'session_revoke_title': 'Révoquer la session',
    'session_revoke_confirm': 'Êtes-vous sûr de vouloir révoquer la session sur',
    'session_reconnect_required': 'L\'utilisateur devra se reconnecter.',
    'session_revoked_success': 'Session révoquée avec succès',
    'session_revoke_error': 'Erreur lors de la révocation de la session',
    'session_no_other': 'Aucune autre session à révoquer',
    'session_revoke_all_title': 'Révoquer toutes les autres sessions',
    'session_revoke_all_confirm': 'Êtes-vous sûr de vouloir révoquer',
    'session_sessions': 'session(s)',
    'session_all_reconnect': 'Tous les utilisateurs devront se reconnecter.',
    'session_revoked_count': 'session(s) révoquée(s)',
    'session_delete_all_title': 'Supprimer toutes les sessions',
    'session_delete_all_confirm': 'ATTENTION ! Ceci supprimera TOUTES vos sessions y compris la session actuelle.\n\nVous devrez vous reconnecter sur tous vos appareils.\n\nVoulez-vous continuer ?',
    'session_all_deleted': 'Toutes les sessions ont été supprimées',
    'session_delete_error': 'Erreur lors de la suppression',
    'session_revoke_btn': 'Révoquer',
    'session_current': 'Session actuelle',
    'session_active': 'Active',
    'session_inactive': 'Inactive',
    'session_version': 'Version',
    'session_last_activity': 'Dernière activité',
    'session_created_at': 'Créée le',
    'session_long_inactive': 'Session inactive depuis longtemps',
    'session_revoke_tooltip': 'Révoquer cette session',
    'session_all_sessions': 'Toutes les sessions',
    'session_refresh': 'Rafraîchir les sessions',
    'session_revoke_all_btn': 'Tout révoquer',
    'session_none': 'Aucune session',
    'session_none_desc': 'Les sessions apparaîtront ici lorsque vous vous connecterez.',
    'session_total_count': 'session(s) totale(s)',
    'session_active_count': 'active(s)',
    'session_inactive_count': 'inactive(s)',
    'session_delete_all_btn': 'Supprimer tout',

    // ── Formulaire adresse (widget) ───────────────────────────────
    'addr_country_region': 'Pays/Région',
    'addr_personal_info_section': 'Informations personnelles',
    'addr_contact_name_hint': 'Nom du contact*',
    'addr_contact_name_helper': 'Veuillez saisir un nom de contact.',
    'addr_contact_name_error': 'Veuillez saisir un nom de contact',
    'addr_phone_hint': 'Numéro de portable*',
    'addr_phone_error_required': 'Numéro requis',
    'addr_phone_error_invalid': 'Numéro invalide',
    'addr_address_section': 'Adresse',
    'addr_street_hint': 'Rue et numéro de la rue*',
    'addr_street_error': 'La rue est requise',
    'addr_complement_hint': 'Appartement, suite, unité, etc. (facultatif)',
    'addr_province_hint': 'Province*',
    'addr_province_error': 'La province est requise',
    'addr_city_hint': 'Ville*',
    'addr_city_error': 'La ville est requise',
    'addr_postal_hint': 'Code postal*',
    'addr_postal_error': 'Le code postal est requis',

    // ── Dialog déconnexion automatique ────────────────────────────
    'autologout_title': 'Déconnexion\nautomatique',
    'autologout_will_logout': 'Vous serez déconnecté dans',
    'autologout_second': 'seconde',
    'autologout_seconds': 'secondes',
    'autologout_inactivity_msg': 'Vous avez été inactif pendant trop longtemps. Cliquez ci-dessous pour rester connecté.',
    'autologout_stay': 'Rester connecté',
    'autologout_logout': 'Se déconnecter',

    // ── Widget genre ──────────────────────────────────────────────
    'gender_select_placeholder': 'Sélectionner le genre',
    'gender_dialog_title': 'Sélectionner le genre',

    // ── Widget téléphone ──────────────────────────────────────────
    'phone_select_country': 'Sélectionner un pays',
    'phone_search_country': 'Rechercher un pays...',
    'phone_label': 'Téléphone',

    // ── Widget Profile Image ───────────────────────────────────────────────
    'change_photo': 'Changer la photo',
    'choose_photo': 'Choisir une photo',
    'camera': 'Appareil photo',
    'gallery': 'Galerie',

    // ── Widget FAQ Item ───────────────────────────────────────────────────
    'faq_question': 'Question',
    'faq_category': 'Catégorie',
    'faq_content_unavailable': 'Contenu non disponible',
    'faq_useful': 'Utile',
    'faq_share': 'Partager',

    // ── Splash Screen ───────────────────────────────────────────────────
    'splash_loading': 'Chargement en cours',
    'splash_version': 'Version 1.0.0',
    'splash_copyright': ' 2026 winzy. Tous droits réservés.',

    // ── Change Password Page ───────────────────────────────────────────
    'change_password_google_title': 'Ouvrir la sécurité Google',
    'change_password_google_desc': 'Pour changer votre mot de passe Google, veuillez:',
    'change_password_google_step1': '1. Copier le lien ci-dessous',
    'change_password_google_step2': '2. Ouvrir votre navigateur',
    'change_password_google_step3': '3. Coller le lien et accéder à la page',
    'change_password_link_copied': 'Lien copié dans le presse-papiers!',
    'change_password_google_account': 'Compte Google',
    'change_password_google_connected': 'Votre compte est connecté via Google',
    'change_password_how_to': 'Comment changer votre mot de passe ?',
    'change_password_google_step1_1': '1. Allez dans votre compte Google',
    'change_password_google_step2_1': '2. Cliquez sur "Sécurité"',
    'change_password_google_step3_1': '3. Sous "Connexion à Google", cliquez sur "Mot de passe"',
    'change_password_google_step4_1': '4. Suivez les instructions pour changer votre mot de passe',
    'change_password_google_warning': 'Le changement de mot de passe doit être effectué directement sur Google pour des raisons de sécurité.',
    'change_password_info_secure': 'Vos informations sont cryptées et sécurisées',

    // ── Session Timeout Values ───────────────────────────────────────
    'session_timeout_5_seconds': '5 secondes',
    'session_timeout_15_minutes': '15 minutes',
    'session_timeout_30_minutes': '30 minutes',
    'session_timeout_1_hour': '1 heure',
    'session_timeout_2_hours': '2 heures',


    // ── Widget Default Address Toggle ──────────────────────────────────────────
    'set_default_address': 'Définir comme adresse de livraison par défaut',

    'payment_card_number_label':       'Numéro de carte',
    'payment_cardholder_label':        'Nom du titulaire',
    'payment_cardholder_hint':         'NOM PRÉNOM',
    'payment_cardholder_required':     'Le nom du titulaire est requis',
    'payment_expiry_label':            'Expiration',
    'payment_expiry_required':         'Date requise',
    'payment_expiry_invalid':          'Format invalide',
    'payment_card_expired':            'Carte expirée',
    'payment_cvv_label':               'CVV',
    'payment_cvv_invalid':             'CVV invalide',
    'payment_card_number_invalid':     'Numéro de carte invalide',
    'payment_card_holder_label_preview': 'TITULAIRE',
    'payment_card_holder_placeholder': 'VOTRE NOM',
    'payment_expires_preview':         'EXPIRE',
    'payment_add_card_btn':            'Ajouter la carte',
    'payment_card_added_success':      'Carte ajoutée avec succès !',
    'payment_paypal_option_title':    'PayPal',
    'payment_paypal_option_subtitle': 'Payer via votre compte PayPal',
    'payment_applepay_option_title':  'Apple Pay / Google Pay',
    'payment_applepay_option_subtitle': 'Paiement rapide via votre téléphone',
    'payment_coming_soon':            'Bientôt disponible',
    'payment_cash_delivery_title': 'Paiement à la livraison',
    'payment_cash_delivery_desc':  'Payez en espèces à la réception de votre commande',

    // ══════════════════════ paypal ════════════════════════════
    'paypal_page_title':       'Lier PayPal',
    'paypal_header_subtitle':  'Payez en toute sécurité avec votre compte PayPal',
    'paypal_email_label':      'Email de votre compte PayPal',
    'paypal_email_hint':       'exemple@paypal.com',
    'paypal_email_required':   'L\'email PayPal est requis',
    'paypal_email_invalid':    'Adresse email invalide',
    'paypal_info_text':        'Entrez l\'adresse email associée à votre compte PayPal. Vos données sont sécurisées et chiffrées.',
    'paypal_link_btn':         'Lier mon compte PayPal',
    'paypal_no_account':       'Vous n\'avez pas de compte PayPal ?',
    'paypal_added_success':    'Compte PayPal lié avec succès !',
    'paypal_already_added':    'Un compte PayPal est déjà lié',
    'paypal_holder_label':    'Nom du titulaire PayPal',
    'paypal_holder_hint':     'Prénom Nom',
    'paypal_holder_required': 'Le nom du titulaire est requis',
  };

  // ════════════════════════════════════════════════════════════════
  //  ENGLISH
  // ════════════════════════════════════════════════════════════════
  static const Map<String, String> _en = {
    'login_title': 'Login',
    'signup_title': 'Sign Up',
    'email': 'Email',
    'password': 'Password',
    'email_required': 'Please enter your email',
    'password_required': 'Please enter your password',
    'invalid_email': 'Please enter a valid email',
    'logout': 'Logout',
    'confirm_logout': 'Are you sure you want to logout?',
    'login': 'Sign In',
    'logging_in': 'Signing in...',
    'continue_google': 'Continue with Google',
    'continue_guest': 'Continue as Guest',
    'no_account': 'Don\'t have an account?',
    'already_account': 'Already have an account?',
    'forgot_password': 'Forgot password?',
    'remember_me': 'Remember me',
    'create_account': 'Create an Account',
    'confirm_password': 'Confirm Password',
    'confirm_password_required': 'Please confirm your password',
    'passwords_not_match': 'Passwords do not match',
    'password_min_length': 'At least 8 characters',
    'password_uppercase': 'At least one uppercase letter',
    'password_lowercase': 'At least one lowercase letter',
    'password_requirements': 'Password does not meet requirements',
    'password_must_contain': 'Password must contain:',
    'profile_complete_later': 'Other information will be completed in your profile later.',
    'agree_terms': 'I agree to the terms and conditions',
    'accept_terms_required': 'Please accept the terms and conditions',
    'signup_success': 'Account created successfully!',
    'verification_email_sent': 'A verification email has been sent to:',
    'verify_before_login': 'Please check your inbox and click the verification link before logging in.',
    'understand': 'OK, I understand',
    'signing_up': 'Signing up...',
    'account_deactivated_error': 'This account has been deactivated and will be deleted in 30 days.',
  'account_deactivated_title': 'Account Deactivated',
  'account_deactivated_message': 'Your account has been deactivated and will be permanently deleted in 30 days. A reactivation email has been sent.',
  'reactivation_email_sent': 'Reactivation email sent',
  'reactivation_email_error': 'Error sending reactivation email',

    // ── Terms and Conditions ──────────────────────────────────────
    'terms_title': 'Terms and Conditions of Use',
    'terms_description': 'Please read these terms and conditions carefully before using the Winzy application.',
    'terms_last_updated': 'Last updated: 18 february 2026',

    'terms_section_1_title': '1. Acceptance of Terms',
    'terms_section_1_content': 'By accessing and using the Winzy application, you agree to be bound by these terms and conditions. If you do not accept these terms, please do not use our service. Continued use of the application after any changes constitutes your acceptance of the new terms.',

    'terms_section_2_title': '2. Use of Service',
    'terms_section_2_content': 'Winzy is an e-commerce platform that allows you to buy and sell products. You agree to use the service lawfully and ethically, not to post fraudulent or misleading content, to respect the rights of other users, and not to attempt to compromise the security of the platform.',

    'terms_section_3_title': '3. Privacy and Personal Data',
    'terms_section_3_content': 'We collect and process your personal data in accordance with our privacy policy. Your information is used solely to enhance your experience on the platform and to process your orders. We never sell your data to third parties. You may request deletion of your data at any time.',

    'terms_section_4_title': '4. Payments and Refunds',
    'terms_section_4_content': 'All payments are processed securely. Displayed prices include all applicable taxes. In case of a dispute regarding an order, our support team is available to assist you. Refunds are processed within 5 to 10 business days depending on your payment method.',

    'terms_section_5_title': '5. Limitation of Liability',
    'terms_section_5_content': 'Winzy strives to ensure the availability and reliability of the service, but cannot be held responsible for temporary service interruptions, content errors, indirect damages resulting from the use of the service, or the actions of third-party sellers on the platform.',

    'terms_conditions': 'Terms and Conditions',

    'close': 'Close',
    'i_agree': 'I Agree',


    'forgot_password_title': 'FORGOT PASSWORD',
    'forgot_password_desc': 'Enter your email address to receive\na password reset link',
    'send_link': 'Send Link',
    'sending': 'Sending...',
    'back_to': 'Back to',
    'login_page': 'login page',
    'email_sent': 'Email Sent!',
    'reset_link_sent': 'A reset link has been sent to',
    'check_inbox_reset': 'Check your inbox and click the link to reset your password',
    'continue': 'Continue',
    'home': 'Home',
    'cart': 'Cart',
    'history': 'History',
    'profile': 'Profile',
    'settings': 'Settings',
    'personal_info': 'Personal Information',
    'addresses': 'Addresses',
    'payment_methods': 'Payment Methods',
    'notification_settings': 'Notification Settings',
    'security': 'Security',
    'language': 'Language',
    'help': 'Help',
    'orders': 'Orders',
    'favorites': 'Favorites',
    'points': 'Points',
    'change_password': 'Change Password',
    'current_password': 'Current Password',
    'new_password': 'New Password',
    'confirm_password_field': 'Confirm Password',
    'two_factor_auth': 'Two-Factor Authentication',
    'biometric_auth': 'Biometric Authentication',
    'active_sessions': 'Active Sessions',
    'payment': 'Payment',
    'order_summary': 'Order Summary',
    'delivery_address': 'Delivery Address',
    'payment_method': 'Payment Method',
    'subtotal': 'Subtotal',
    'shipping': 'Shipping',
    'discount': 'Discount',
    'total': 'Total',
    'pay': 'Pay',
    'credit_card': 'Credit Card',
    'paypal': 'PayPal',
    'apple_pay': 'Apple Pay',
    'session_warning': 'Session Warning',
    'inactivity_warning': 'You will be logged out due to inactivity',
    'stay_logged_in': 'Stay Logged In',
    'session_expired': 'Your session has expired',
    'inactivity_detected': 'Inactivity Detected',
    'remaining_time': 'Remaining Time',
    'success': 'Success',
    'error': 'Error',
    'loading': 'Loading...',
    'no_data': 'No data',
    'save': 'Save',
    'edit': 'Edit',
    'delete': 'Delete',
    'confirm': 'Confirm',
    'cancel': 'Cancel',
    'back': 'Back',
    'ok': 'OK',
    'add': 'Add',
    'by_default': 'Default',

    // ── Cart ──────────────────────────────────────────────────────
    'cart_title': 'Cart',
    'select_all': 'All',
    'summary': 'Summary',
    'article': 'item',
    'articles': 'items',
    'reductions': 'Discounts',
    'estimated_total': 'Estimated Total',
    'checkout': 'Checkout',
    'empty_cart': 'Your cart is empty',
    'item_removed': 'Item removed',
    'quantity': 'Quantity',
    'items_selected': 'items selected',

    // ── Addresses ─────────────────────────────────────────────────
    'delivery_address_title': 'Delivery Address',
    'add_new_address': 'Add New Address',
    'add_address_title': 'Add New Address',
    'edit_address_title': 'Edit Address',
    'default_address': 'Default Address',
    'set_as_default': 'Default',
    'no_addresses': 'No Addresses',
    'add_first_address': 'Add your first delivery address',
    'loading_addresses': 'Loading addresses...',
    'delete_address': 'Delete Address',
    'confirm_delete_address': 'Are you sure you want to delete this notification?',
    'address_saved': 'Address saved successfully!',
    'address_updated': 'Address updated successfully!',
    'address_default_updated': 'Your default address has been updated',
    'address_default_title': 'Default Address',
    'address_load_error': 'Error loading addresses',
    'new_badge': 'New!',
    'all_info_encrypted': 'All your information is encrypted',
    'info_encrypted_secure': 'Your information is encrypted and secure',
    'update_address_info': 'Update your address information',

    // ── Address Form ──────────────────────────────────────────────
    'section_contact_info': 'Contact Information',
    'section_address_info': 'Address Information',
    'contact_name': 'Contact Name',
    'contact_name_required': 'Please enter a contact name',
    'hint_contact_name': 'E.g.: John Doe',
    'phone': 'Phone',
    'phone_required': 'Please enter a phone number',
    'hint_phone': 'E.g.: 20 123 456',
    'street': 'Street / Address',
    'street_required': 'Please enter an address',
    'hint_street': 'E.g.: 12 Main Street',
    'complement': 'Address Complement',
    'hint_complement': 'E.g.: Apartment 4B, Building C',
    'province': 'Province / State',
    'province_required': 'Please enter a province',
    'hint_province': 'E.g.: Tunis',
    'city': 'City',
    'city_required': 'Please enter a city',
    'hint_city': 'E.g.: Tunis',
    'postal_code': 'Postal Code',
    'postal_code_required': 'Please enter a postal code',
    'hint_postal_code': 'E.g.: 1000',
    'country': 'Country',
    'search_country': 'Search country...',
    'save_address_btn': 'Save Address',
    'saving_address_btn': 'Saving...',
    'update_address_btn': 'Update Address',
    'updating_address_btn': 'Updating...',
    'set_default_label': 'Set as default address',
    'set_default_description': 'This address will be used automatically for your orders',

    // ── Help Center ───────────────────────────────────────────────
    'help_center_title': 'Help Center',
    'help_search_hint': 'Search for help...',
    'help_category_all': 'All',
    'help_empty_title': 'No help found',
    'help_empty_subtitle': 'Try modifying your search or changing category',
    'help_faq_content_unavailable': 'Content unavailable',
    'help_faq_load_error': 'Error loading FAQs',
    'help_support_fab': 'Support',
    'help_contact_title': 'Contact Support',
    'help_chat_title': 'Live Chat',
    'help_chat_subtitle': 'Chat with an agent now',
    'help_chat_soon': 'Live chat coming soon!',
    'help_phone_title': 'Phone',
    'help_phone_subtitle': 'Call us at +216 70 000 000',
    'help_phone_unavailable': 'Phone app not available on this device',
    'help_email_title': 'Email',
    'help_email_subtitle': 'Send us an email at support@winzy.com',
    'help_email_copied': 'Email copied to clipboard!',
    'help_email_fallback': 'Email: support@winzy.com',
    'help_category_commandes': 'Orders',
    'help_category_paiement': 'Payment',
    'help_category_compte': 'Account',
    'help_category_livraison': 'Delivery',
    'help_category_retours': 'Returns',
    'help_category_securite': 'Security',
    'help_category_application': 'App',

    // ── Notification Settings ─────────────────────────────────────
    'notif_settings_title': 'Notification Settings',
    'notif_save_tooltip': 'Save settings',
    'notif_saved_success': 'Settings saved successfully!',
    'notif_section_general': 'General Notifications',
    'notif_push_title': 'Push Notifications',
    'notif_push_subtitle': 'Receive notifications on your device',
    'notif_email_title': 'Email Notifications',
    'notif_email_subtitle': 'Receive notifications by email',
    'notif_section_orders': 'Orders & Deliveries',
    'notif_orders_title': 'Order Updates',
    'notif_orders_subtitle': 'Mark all as read',
    'notif_section_marketing': 'Marketing & Promotions',
    'notif_promo_title': 'Promotional Offers',
    'notif_promo_subtitle': 'Discounts and special deals',
    'notif_new_products_title': 'New Products',
    'notif_new_products_subtitle': 'Discover new arrivals',
    'notif_price_drops_title': 'Price Drops',
    'notif_price_drops_subtitle': 'Alerts when prices decrease',
    'notif_newsletter_title': 'Newsletter',
    'notif_newsletter_subtitle': 'Weekly news and tips',
    'notif_section_account': 'Account & Security',
    'notif_account_title': 'Account Updates',
    'notif_account_subtitle': 'Important changes to your account',
    'notif_security_title': 'Security Alerts',
    'notif_security_subtitle': 'Suspicious activity and logins',

    // ── Payment Methods ───────────────────────────────────────────
    'payment_methods_title': 'Payment Methods',
    'payment_manage_info': 'Manage your cards and payment preferences',
    'payment_add_fab': 'Add',
    'payment_security_title': 'Payment Security',
    'payment_security_desc': 'All your transactions are secured with SSL encryption. Your banking information is never stored on our servers.',
    'payment_pci_certified': 'PCI DSS Certified',
    'payment_set_default': 'Set as default',
    'payment_expires': 'Expires',
    'payment_add_sheet_title': 'Add Payment Method',
    'payment_card_option_title': 'Credit Card',
    'payment_card_option_subtitle': 'Add a new Visa, Mastercard...',
    'payment_cash_option_title': 'Cash on Delivery',
    'payment_cash_option_subtitle': 'Enable payment on delivery',
    'payment_cash_activated': 'Cash on delivery activated!',
    'payment_add_card_title': 'Add Credit Card',
    'payment_add_card_content': 'Card form to be implemented with a payment service.',
    'payment_edit_coming_soon': 'Payment method modification to be implemented.',
    'payment_add_coming_soon': 'Card addition to be implemented.',
    'payment_delete_title': 'Delete Payment Method',
    'payment_delete_confirm': 'Are you sure you want to delete this payment method?',
    'payment_deleted_success': 'Payment method deleted',
    'payment_set_default_success': 'Payment method set as default',
    'payment_cash_description': 'Pay in cash or by card upon delivery',

    // ── Edit Profile ──────────────────────────────────────────────
    'edit_profile_title': 'Edit Profile',
    'edit_profile_first_name': 'First Name',
    'edit_profile_hint_first_name': 'E.g.: John',
    'edit_profile_last_name': 'Last Name',
    'edit_profile_hint_last_name': 'E.g.: Doe',
    'edit_profile_email': 'Email',
    'edit_profile_email_readonly': 'Email cannot be changed for security reasons',
    'edit_profile_phone': 'Phone',
    'edit_profile_gender': 'Gender',
    'edit_profile_saving': 'Saving...',
    'edit_profile_save_btn': 'Save',
    'edit_profile_success': 'Profile updated successfully!',
    'edit_profile_error': 'Error updating profile',
    'edit_profile_notif_title': 'Profile updated',
    'edit_profile_notif_body': 'Your information has been saved successfully',
    'edit_profile_first_name_required': 'Please enter your first name',
    'edit_profile_last_name_required': 'Please enter your last name',
    'edit_profile_phone_required': 'Please enter your phone number',
    'edit_profile_section_personal': 'Personal Information',
    'edit_profile_section_contact': 'Contact',
    'photo_change_title':    'Change profile photo',
    'photo_from_gallery':    'Choose from gallery',
    'photo_from_camera':     'Take a photo',
    'photo_remove':          'Remove photo',
    'photo_upload_success':  'Profile photo updated!',
    'photo_upload_error':    'Error uploading photo',
    'photo_removed_success': 'Profile photo removed',

    // ── Security ──────────────────────────────────────────────────
    'security_title': 'Security',
    'section_session': 'Session',
    'section_confidentiality': 'Privacy',
    'security_subtitle': 'Manage your account security',
    'security_google_account': 'Google Account',
    'security_google_connected': 'Your account is connected via Google',
    'security_google_how_to': 'How to change your password?',
    'security_google_step1': 'Go to your Google account',
    'security_google_step2': 'Click on "Security"',
    'security_google_step3': 'Under "Signing in to Google", click "Password"',
    'security_google_step4': 'Follow the instructions to change your password',
    'security_google_warning': 'Password changes must be made directly on Google for security reasons.',
    'security_open_google': 'Open Google Security',
    'security_google_dialog_title': 'Open Google Security',
    'security_google_dialog_step1': '1. Copy the link below',
    'security_google_dialog_step2': '2. Open your browser',
    'security_google_dialog_step3': '3. Paste the link and access the page',
    'security_link_copied': 'Link copied to clipboard!',
    'security_unsupported_title': 'Sign-in method not supported',
    'security_unsupported_desc': 'Your current sign-in method does not allow changing the password from this app.',
    'security_auth_section': 'Authentication',
    'security_two_factor_subtitle': 'Adds an extra layer of security',
    'security_biometric_subtitle': 'Use your fingerprint or face',
    'security_change_password_subtitle': 'Update your password',
    'security_session_section': 'Session',
    'security_auto_logout_title': 'Auto Logout',
    'security_auto_logout_subtitle': 'Logout after inactivity',
    'security_inactivity_delay': 'Inactivity Delay',
    'security_inactivity_subtitle': 'Time before automatic logout',
    'security_active_sessions_subtitle': 'Manage your active connections',
    'security_privacy_section': 'Privacy',
    'security_login_notif_title': 'Login Notifications',
    'security_login_notif_subtitle': 'Get notified of new logins',
    'security_download_data': 'Download Your Data',
    'security_download_subtitle': 'Export your personal information',
    'security_download_preparing': 'Preparing download...',
    'security_download_success': 'Data exported successfully!',
    'security_download_confirm_title': 'Download Your Data',
    'security_download_confirm_body': 'Do you want to download all your personal information?',
    'security_download_btn': 'Download',
    'security_share_btn': 'Share',
    'security_delete_account': 'Delete Account',
    'security_delete_account_subtitle': 'Permanently delete your account',
    'security_delete_account_confirm': 'Are you sure you want to delete your account? This action is irreversible and all your data will be lost.',
    'delete_account_dialog_title': 'Delete my account',
    'delete_account_dialaccount_deactivated_messageog_subtitle': 'Your account will be deactivated. You can recover it within 30 days using the account reactivation email sent to your email address.',
    'delete_account_reason_label': 'Why do you want to delete your account?',
    'delete_reason_1': 'I no longer use the app',
    'delete_reason_2': 'I created another account',
    'delete_reason_3': 'The app does not meet my needs',
    'delete_reason_4': 'I am concerned about my privacy',
    'delete_reason_5': 'I receive too many notifications',
    'delete_reason_other': 'Other (please specify)',
    'delete_other_placeholder': 'Describe your reason here...',
    'delete_confirm_instruction': 'To confirm the permanent deletion of your account:',
    'delete_confirm_type_label': 'Type',
    'delete_confirm_word': 'DELETE',
    'delete_account_btn': 'Delete account',
    'account_deactivated_message1': 'Your account has been deactivated. It will be permanently deleted in 30 days.',
    'security_auto_logout_activated': 'Auto logout activated',
    'security_auto_logout_deactivated': 'Auto logout deactivated',
    'security_delay_changed': 'Inactivity delay changed to',

    // ── Main Layout ───────────────────────────────────────────────
    'main_smart_market': 'Winzy',
    'main_purchase_history': 'Purchase History',
    'main_my_profile': 'My Profile',
    'main_login_required_title': 'Login Required',
    'main_login_required_body': 'You must be logged in to access this feature.',
    'main_later': 'Later',
    'main_cart_summary': 'Cart Summary',
    'main_selected_items': 'Selected Items',
    'main_start_shopping': 'Start Shopping',
    'main_add_to_cart': 'Add items to start shopping',

    // ── Notifications page ────────────────────────────────────────
    'notif_page_mark_all_read': 'Mark all as read',
    'notif_page_delete_all': 'Delete all',
    'notif_page_empty_title': 'No notifications',
    'notif_page_empty_subtitle': 'You have no notifications at the moment',
    'notif_page_delete_confirm_title': 'Delete all',
    'notif_page_delete_confirm_body': 'Are you sure you want to delete all your notifications?',
    'notif_page_time_ago_minutes': '{n} minute(s) ago',
    'notif_page_time_ago_hours': '{n} hour(s) ago',
    'notif_page_time_ago_days': '{n} day(s) ago',
    'notif_page_time_ago_default': 'Some time ago',
    'notif_page_mark_error': 'Error marking notification',
    'notif_page_delete_error': 'Error deleting notification',

    // ── Active Sessions ───────────────────────────────────────────
    'session_cannot_revoke_current': 'Cannot revoke the current session',
    'session_revoke_title': 'Revoke Session',
    'session_revoke_confirm': 'Are you sure you want to revoke the session on',
    'session_reconnect_required': 'The user will need to sign in again.',
    'session_revoked_success': 'Session revoked successfully',
    'session_revoke_error': 'Error revoking the session',
    'session_no_other': 'No other sessions to revoke',
    'session_revoke_all_title': 'Revoke all other sessions',
    'session_revoke_all_confirm': 'Are you sure you want to revoke',
    'session_sessions': 'session(s)',
    'session_all_reconnect': 'All users will need to sign in again.',
    'session_revoked_count': 'session(s) revoked',
    'session_delete_all_title': 'Delete all sessions',
    'session_delete_all_confirm': 'WARNING! This will delete ALL your sessions including the current one.\n\nYou will need to sign in again on all your devices.\n\nDo you want to continue?',
    'session_all_deleted': 'All sessions have been deleted',
    'session_delete_error': 'Error deleting sessions',
    'session_revoke_btn': 'Revoke',
    'session_current': 'Current session',
    'session_active': 'Active',
    'session_inactive': 'Inactive',
    'session_version': 'Version',
    'session_last_activity': 'Last activity',
    'session_created_at': 'Created on',
    'session_long_inactive': 'Session inactive for a long time',
    'session_revoke_tooltip': 'Revoke this session',
    'session_all_sessions': 'All sessions',
    'session_refresh': 'Refresh sessions',
    'session_revoke_all_btn': 'Revoke all',
    'session_none': 'No sessions',
    'session_none_desc': 'Sessions will appear here when you sign in.',
    'session_total_count': 'total session(s)',
    'session_active_count': 'active',
    'session_inactive_count': 'inactive',
    'session_delete_all_btn': 'Delete all',

    // ── Address Form Widget ───────────────────────────────────────
    'addr_country_region': 'Country/Region',
    'addr_personal_info_section': 'Personal Information',
    'addr_contact_name_hint': 'Contact name*',
    'addr_contact_name_helper': 'Please enter a contact name.',
    'addr_contact_name_error': 'Please enter a contact name',
    'addr_phone_hint': 'Mobile number*',
    'addr_phone_error_required': 'Number required',
    'addr_phone_error_invalid': 'Invalid number',
    'addr_address_section': 'Address',
    'addr_street_hint': 'Street and street number*',
    'addr_street_error': 'Street is required',
    'addr_complement_hint': 'Apartment, suite, unit, etc. (optional)',
    'addr_province_hint': 'Province*',
    'addr_province_error': 'Province is required',
    'addr_city_hint': 'City*',
    'addr_city_error': 'City is required',
    'addr_postal_hint': 'Postal code*',
    'addr_postal_error': 'Postal code is required',

    // ── Auto Logout Dialog ────────────────────────────────────────
    'autologout_title': 'Auto\nLogout',
    'autologout_will_logout': 'You will be logged out in',
    'autologout_second': 'second',
    'autologout_seconds': 'seconds',
    'autologout_inactivity_msg': 'You have been inactive for too long. Click below to stay logged in.',
    'autologout_stay': 'Stay Logged In',
    'autologout_logout': 'Log Out',

    // ── Gender Widget ─────────────────────────────────────────────
    'gender_select_placeholder': 'Select gender',
    'gender_dialog_title': 'Select gender',

    // ── Phone Widget ──────────────────────────────────────────────
    'phone_select_country': 'Select a country',
    'phone_search_country': 'Search for a country...',
    'phone_label': 'Phone',

      // ── Widget Profile Image ───────────────────────────────────────────────
    'change_photo': 'Change Photo',
    'choose_photo': 'Choose Photo',
    'camera': 'Camera',
    'gallery': 'Gallery',
    
    // ── Widget FAQ Item ───────────────────────────────────────────────────
    'faq_question': 'Question',
    'faq_category': 'Category',
    'faq_content_unavailable': 'Content unavailable',
    'faq_useful': 'Useful',
    'faq_share': 'Share',
    
    // ── Splash Screen ───────────────────────────────────────────────────
    'splash_loading': 'Loading',
    'splash_version': 'Version 1.0.0',
    'splash_copyright': ' 2026 winzy. All rights reserved.',
    
    // ── Change Password Page ───────────────────────────────────────────
    'change_password_google_title': 'Open Google Security',
    'change_password_google_desc': 'To change your Google password, please:',
    'change_password_google_step1': '1. Copy the link below',
    'change_password_google_step2': '2. Open your browser',
    'change_password_google_step3': '3. Paste the link and access the page',
    'change_password_link_copied': 'Link copied to clipboard!',
    'change_password_google_account': 'Google Account',
    'change_password_google_connected': 'Your account is connected via Google',
    'change_password_how_to': 'How to change your password?',
    'change_password_google_step1_1': '1. Go to your Google account',
    'change_password_google_step2_1': '2. Click on "Security"',
    'change_password_google_step3_1': '3. Under "Signing in to Google", click "Password"',
    'change_password_google_step4_1': '4. Follow instructions to change your password',
    'change_password_google_warning': 'Password changes must be made directly on Google for security reasons.',
    'change_password_info_secure': 'Your information is encrypted and secure',

    // ── Session Timeout Values ───────────────────────────────────────
    'session_timeout_5_seconds': '5 seconds',
    'session_timeout_15_minutes': '15 minutes',
    'session_timeout_30_minutes': '30 minutes',
    'session_timeout_1_hour': '1 hour',
    'session_timeout_2_hours': '2 hours',

    // ── Widget Default Address Toggle ──────────────────────────────────────────
    'set_default_address': 'Set as default shipping address',


    'payment_card_number_label':       'Card number',
    'payment_cardholder_label':        'Cardholder name',
    'payment_cardholder_hint':         'FIRST LAST',
    'payment_cardholder_required':     'Cardholder name is required',
    'payment_expiry_label':            'Expiry date',
    'payment_expiry_required':         'Expiry date required',
    'payment_expiry_invalid':          'Invalid format',
    'payment_card_expired':            'Card is expired',
    'payment_cvv_label':               'CVV',
    'payment_cvv_invalid':             'Invalid CVV',
    'payment_card_number_invalid':     'Invalid card number',
    'payment_card_holder_label_preview': 'CARD HOLDER',
    'payment_card_holder_placeholder': 'YOUR NAME',
    'payment_expires_preview':         'EXPIRES',
    'payment_add_card_btn':            'Add card',
    'payment_card_added_success':      'Card added successfully!',
    'payment_paypal_option_title':    'PayPal',
    'payment_paypal_option_subtitle': 'Pay via your PayPal account',
    'payment_paypal_add_success':    'PayPal account added successfully!',
    'payment_paypal_add_error':      'Error adding PayPal account',
    'payment_paypal_email_required':  'PayPal email is required',
    'payment_paypal_email_invalid':   'Please enter a valid PayPal email',
    'payment_paypal_name_required':   'Account holder name is required',
    'payment_paypal_terms_required': 'You must accept the terms of use',
    'payment_applepay_option_title':  'Apple Pay / Google Pay',
    'payment_applepay_option_subtitle': 'Fast payment via your phone',
    'payment_coming_soon':            'Coming soon',
    'payment_cash_delivery_title': 'Cash on delivery',
    'payment_cash_delivery_desc':  'Pay in cash when you receive your order',

    // ══════════════════════ paypal ════════════════════════════
    'paypal_page_title':       'Link PayPal',
    'paypal_header_subtitle':  'Pay securely with your PayPal account',
    'paypal_email_label':      'Your PayPal account email',
    'paypal_email_hint':       'example@paypal.com',
    'paypal_email_required':   'PayPal email is required',
    'paypal_email_invalid':    'Invalid email address',
    'paypal_info_text':        'Enter the email address linked to your PayPal account. Your data is secured and encrypted.',
    'paypal_link_btn':         'Link my PayPal account',
    'paypal_no_account':       'Don\'t have a PayPal account?',
    'paypal_added_success':    'PayPal account linked successfully!',
    'paypal_already_added':    'A PayPal account is already linked',
    'paypal_holder_label':    'PayPal account holder name',
    'paypal_holder_hint':     'First Last',
    'paypal_holder_required': 'Holder name is required',
  };
  //  ARABIC
  // ════════════════════════════════════════════════════════════════
  static const Map<String, String> _ar = {
    'login_title': 'تسجيل الدخول',
    'signup_title': 'التسجيل',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'email_required': 'يرجى إدخال بريدك الإلكتروني',
    'password_required': 'يرجى إدخال كلمة المرور',
    'invalid_email': 'يرجى إدخال بريد إلكتروني صحيح',
    'logout': 'تسجيل الخروج',
    'confirm_logout': 'هل أنت متأكد من رغبتك في تسجيل الخروج؟',
    'login': 'تسجيل الدخول',
    'logging_in': 'جاري تسجيل الدخول...',
    'continue_google': 'الاستمرار مع Google',
    'continue_guest': 'الاستمرار كضيف',
    'no_account': 'لا تملك حساباً؟',
    'already_account': 'هل لديك حساب بالفعل؟',
    'forgot_password': 'هل نسيت كلمة المرور؟',
    'remember_me': 'تذكرني',
    'create_account': 'إنشاء حساب',
    'confirm_password': 'تأكيد كلمة المرور',
    'confirm_password_required': 'يرجى تأكيد كلمة المرور',
    'passwords_not_match': 'كلمات المرور غير متطابقة',
    'password_min_length': 'على الأقل 8 أحرف',
    'password_uppercase': 'حرف كبير واحد على الأقل',
    'password_lowercase': 'حرف صغير واحد على الأقل',
    'password_requirements': 'كلمة المرور لا تفي بالمتطلبات',
    'password_must_contain': 'يجب أن تحتوي كلمة المرور على:',
    'profile_complete_later': 'سيتم إكمال المعلومات الأخرى في ملفك الشخصي لاحقاً.',
    'agree_terms': 'أوافق على شروط الاستخدام',
    'accept_terms_required': 'يرجى قبول شروط الاستخدام',
    'signup_success': 'تم إنشاء الحساب بنجاح!',
    'verification_email_sent': 'تم إرسال بريد التحقق إلى:',
    'verify_before_login': 'يرجى التحقق من صندوق الوارد والنقر على رابط التحقق قبل تسجيل الدخول.',
    'understand': 'حسناً، فهمت',
    'signing_up': 'جاري التسجيل...',
    'account_deactivated_error': 'تم تعطيل هذا الحساب وسيتم حذفه خلال 30 يوماً.',
    'account_deactivated_title': 'الحساب معطل',
    'account_deactivated_message': 'تم تعطيل حسابك وسيتم حذفه نهائياً خلال 30 يوماً. تم إرسال بريد إلكتروني لإعادة التنشيط.',
    'reactivation_email_sent': 'تم إرسال بريد إلكتروني لإعادة التنشيط',
    'reactivation_email_error': 'خطأ في إرسال بريد إلكتروني لإعادة التنشيط',
    // ── الشروط والأحكام ───────────────────────────────────────────
    'terms_title': 'شروط وأحكام الاستخدام',
    'terms_description': 'يرجى قراءة هذه الشروط والأحكام بعناية قبل استخدام تطبيق Winzy.',
    'terms_last_updated': 'آخر تحديث :18 فبراير 2026',

    'terms_section_1_title': '1. قبول الشروط',
    'terms_section_1_content': 'بالوصول إلى تطبيق Winzy واستخدامه، فإنك توافق على الالتزام بهذه الشروط والأحكام العامة للاستخدام. إذا لم توافق على هذه الشروط، يرجى عدم استخدام خدمتنا. يُعدّ استمرارك في استخدام التطبيق بعد أي تعديل قبولاً منك للشروط الجديدة.',

    'terms_section_2_title': '2. استخدام الخدمة',
    'terms_section_2_content': 'Winzy هي منصة تجارة إلكترونية تتيح لك شراء المنتجات وبيعها. تلتزم باستخدام الخدمة بشكل قانوني وأخلاقي، وعدم نشر محتوى احتيالي أو مضلل، واحترام حقوق المستخدمين الآخرين، وعدم محاولة المساس بأمن المنصة.',

    'terms_section_3_title': '3. الخصوصية والبيانات الشخصية',
    'terms_section_3_content': 'نقوم بجمع بياناتك الشخصية ومعالجتها وفقاً لسياسة الخصوصية الخاصة بنا. تُستخدم معلوماتك فقط لتحسين تجربتك على المنصة ومعالجة طلباتك. لا نبيع بياناتك أبداً لأطراف ثالثة. يمكنك طلب حذف بياناتك في أي وقت.',

    'terms_section_4_title': '4. المدفوعات والمبالغ المستردة',
    'terms_section_4_content': 'تتم معالجة جميع المدفوعات بشكل آمن. تشمل الأسعار المعروضة جميع الضرائب المطبقة. في حالة وجود نزاع بشأن طلبية، يتوفر فريق الدعم لمساعدتك. تتم معالجة المبالغ المستردة في غضون 5 إلى 10 أيام عمل وفقاً لطريقة الدفع الخاصة بك.',

    'terms_section_5_title': '5. تحديد المسؤولية',
    'terms_section_5_content': 'يسعى Winzy  لضمان توفر الخدمة وموثوقيتها، إلا أنه لا يمكن مساءلته عن انقطاعات الخدمة المؤقتة، أو أخطاء المحتوى، أو الأضرار غير المباشرة الناجمة عن استخدام الخدمة، أو تصرفات البائعين الأطراف الثالثة على المنصة.',

    'terms_conditions': 'الشروط والأحكام',

    'close': 'إغلاق',
    'i_agree': 'أوافق',


    'forgot_password_title': 'نسيت كلمة المرور',
    'forgot_password_desc': 'أدخل بريدك الإلكتروني لتلقي\nرابط استرجاع كلمة المرور',
    'send_link': 'إرسال الرابط',
    'sending': 'جاري الإرسال...',
    'back_to': 'العودة إلى',
    'login_page': 'صفحة تسجيل الدخول',
    'email_sent': 'تم إرسال البريد!',
    'reset_link_sent': 'تم إرسال رابط الاستعادة إلى',
    'check_inbox_reset': 'تحقق من صندوق الوارد وانقر على الرابط لاستعادة كلمة المرور',
    'continue': 'متابعة',
    'home': 'الرئيسية',
    'cart': 'عربة التسوق',
    'history': 'السجل',
    'profile': 'الملف الشخصي',
    'settings': 'الإعدادات',
    'personal_info': 'المعلومات الشخصية',
    'addresses': 'العناوين',
    'payment_methods': 'طرق الدفع',
    'notification_settings': 'إعدادات الإشعارات',
    'security': 'الأمان',
    'language': 'اللغة',
    'help': 'مساعدة',
    'orders': 'الطلبات',
    'favorites': 'المفضلة',
    'points': 'النقاط',
    'change_password': 'تغيير كلمة المرور',
    'current_password': 'كلمة المرور الحالية',
    'new_password': 'كلمة المرور الجديدة',
    'confirm_password_field': 'تأكيد كلمة المرور',
    'two_factor_auth': 'المصادقة الثنائية',
    'biometric_auth': 'المصادقة البيومترية',
    'active_sessions': 'الجلسات النشطة',
    'payment': 'الدفع',
    'order_summary': 'ملخص الطلب',
    'delivery_address': 'عنوان التسليم',
    'payment_method': 'طريقة الدفع',
    'subtotal': 'المجموع الفرعي',
    'shipping': 'الشحن',
    'discount': 'الخصم',
    'total': 'الإجمالي',
    'pay': 'ادفع',
    'credit_card': 'بطاقة ائتمان',
    'paypal': 'PayPal',
    'apple_pay': 'Apple Pay',
    'session_warning': 'تحذير الجلسة',
    'inactivity_warning': 'سيتم تسجيل خروجك بسبب عدم النشاط',
    'stay_logged_in': 'البقاء متصلاً',
    'session_expired': 'انتهت صلاحية جلستك',
    'inactivity_detected': 'تم اكتشاف عدم النشاط',
    'remaining_time': 'الوقت المتبقي',
    'success': 'نجاح',
    'error': 'خطأ',
    'loading': 'جاري التحميل...',
    'no_data': 'لا توجد بيانات',
    'save': 'حفظ',
    'edit': 'تعديل',
    'delete': 'حذف',
    'confirm': 'تأكيد',
    'cancel': 'إلغاء',
    'back': 'رجوع',
    'ok': 'حسناً',
    'add': 'إضافة',
    'by_default': 'افتراضي',

    // ── عربة التسوق ───────────────────────────────────────────────
    'cart_title': 'عربة التسوق',
    'select_all': 'الكل',
    'summary': 'الملخص',
    'article': 'منتج',
    'articles': 'منتجات',
    'reductions': 'الخصومات',
    'estimated_total': 'الإجمالي المقدر',
    'checkout': 'إتمام الطلب',
    'empty_cart': 'عربة التسوق فارغة',
    'item_removed': 'تم حذف المنتج',
    'quantity': 'الكمية',
    'items_selected': 'منتجات مختارة',

    // ── العناوين ──────────────────────────────────────────────────
    'delivery_address_title': 'عنوان التسليم',
    'add_new_address': 'إضافة عنوان جديد',
    'add_address_title': 'إضافة عنوان جديد',
    'edit_address_title': 'تعديل العنوان',
    'default_address': 'العنوان الافتراضي',
    'set_as_default': 'افتراضي',
    'no_addresses': 'لا توجد عناوين',
    'add_first_address': 'أضف عنوان التسليم الأول',
    'loading_addresses': 'جاري تحميل العناوين...',
    'delete_address': 'حذف العنوان',
    'confirm_delete_address': 'هل أنت متأكد من رغبتك في حذف هذا الإشعار؟',
    'address_saved': 'تم حفظ العنوان بنجاح!',
    'address_updated': 'تم تحديث العنوان بنجاح!',
    'address_default_updated': 'تم تحديث عنوانك الافتراضي',
    'address_default_title': 'العنوان الافتراضي',
    'address_load_error': 'خطأ في تحميل العناوين',
    'new_badge': 'جديد!',
    'all_info_encrypted': 'جميع معلوماتك مشفرة',
    'info_encrypted_secure': 'معلوماتك مشفرة وآمنة',
    'update_address_info': 'قم بتحديث معلومات عنوانك',

    // ── نموذج العنوان ─────────────────────────────────────────────
    'section_contact_info': 'معلومات الاتصال',
    'section_address_info': 'معلومات العنوان',
    'contact_name': 'اسم جهة الاتصال',
    'contact_name_required': 'يرجى إدخال اسم جهة الاتصال',
    'hint_contact_name': 'مثال: أحمد بن علي',
    'phone': 'الهاتف',
    'phone_required': 'يرجى إدخال رقم الهاتف',
    'hint_phone': 'مثال: 20 123 456',
    'street': 'الشارع / العنوان',
    'street_required': 'يرجى إدخال العنوان',
    'hint_street': 'مثال: 12 شارع الحبيب بورقيبة',
    'complement': 'مكمّل العنوان',
    'hint_complement': 'مثال: شقة 4ب، مبنى ج',
    'province': 'المحافظة / الولاية',
    'province_required': 'يرجى إدخال المحافظة',
    'hint_province': 'مثال: تونس',
    'city': 'المدينة',
    'city_required': 'يرجى إدخال المدينة',
    'hint_city': 'مثال: تونس',
    'postal_code': 'الرمز البريدي',
    'postal_code_required': 'يرجى إدخال الرمز البريدي',
    'hint_postal_code': 'مثال: 1000',
    'country': 'البلد',
    'search_country': 'البحث عن بلد...',
    'save_address_btn': 'حفظ العنوان',
    'saving_address_btn': 'جاري الحفظ...',
    'update_address_btn': 'تحديث العنوان',
    'updating_address_btn': 'جاري التحديث...',
    'set_default_label': 'تعيين كعنوان افتراضي',
    'set_default_description': 'سيتم استخدام هذا العنوان تلقائياً في طلباتك',

    // ── مركز المساعدة ─────────────────────────────────────────────
    'help_center_title': 'مركز المساعدة',
    'help_search_hint': 'ابحث عن مساعدة...',
    'help_category_all': 'الكل',
    'help_empty_title': 'لم يتم العثور على نتائج',
    'help_empty_subtitle': 'حاول تعديل بحثك أو تغيير الفئة',
    'help_faq_content_unavailable': 'المحتوى غير متاح',
    'help_faq_load_error': 'خطأ في تحميل الأسئلة الشائعة',
    'help_support_fab': 'الدعم',
    'help_contact_title': 'التواصل مع الدعم',
    'help_chat_title': 'الدردشة المباشرة',
    'help_chat_subtitle': 'تحدث مع وكيل الآن',
    'help_chat_soon': 'الدردشة المباشرة قريباً!',
    'help_phone_title': 'الهاتف',
    'help_phone_subtitle': 'اتصل بنا على 000 000 70 216+',
    'help_phone_unavailable': 'تطبيق الهاتف غير متاح على هذا الجهاز',
    'help_email_title': 'البريد الإلكتروني',
    'help_email_subtitle': 'راسلنا على support@winzy.com',
    'help_email_copied': 'تم نسخ البريد الإلكتروني!',
    'help_email_fallback': 'البريد الإلكتروني: support@winzy.com',
    'help_category_commandes': 'الطلبات',
    'help_category_paiement': 'الدفع',
    'help_category_compte': 'الحساب',
    'help_category_livraison': 'التوصيل',
    'help_category_retours': 'المرتجعات',
    'help_category_securite': 'الأمان',
    'help_category_application': 'التطبيق',

    // ── إعدادات الإشعارات ─────────────────────────────────────────
    'notif_settings_title': 'إعدادات الإشعارات',
    'notif_save_tooltip': 'حفظ الإعدادات',
    'notif_saved_success': 'تم حفظ الإعدادات بنجاح!',
    'notif_section_general': 'الإشعارات العامة',
    'notif_push_title': 'إشعارات الدفع',
    'notif_push_subtitle': 'تلقي الإشعارات على جهازك',
    'notif_email_title': 'إشعارات البريد الإلكتروني',
    'notif_email_subtitle': 'تلقي الإشعارات عبر البريد الإلكتروني',
    'notif_section_orders': 'الطلبات والتوصيل',
    'notif_orders_title': 'تحديثات الطلب',
    'notif_orders_subtitle': 'تحديد الكل كمقروء',
    'notif_section_marketing': 'التسويق والعروض',
    'notif_promo_title': 'العروض الترويجية',
    'notif_promo_subtitle': 'الخصومات والعروض الخاصة',
    'notif_new_products_title': 'منتجات جديدة',
    'notif_new_products_subtitle': 'اكتشف أحدث المنتجات',
    'notif_price_drops_title': 'انخفاض الأسعار',
    'notif_price_drops_subtitle': 'تنبيهات عند انخفاض الأسعار',
    'notif_newsletter_title': 'النشرة الإخبارية',
    'notif_newsletter_subtitle': 'أخبار ونصائح أسبوعية',
    'notif_section_account': 'الحساب والأمان',
    'notif_account_title': 'تحديثات الحساب',
    'notif_account_subtitle': 'تغييرات مهمة في حسابك',
    'notif_security_title': 'تنبيهات الأمان',
    'notif_security_subtitle': 'الأنشطة المشبوهة وتسجيلات الدخول',

    // ── طرق الدفع ─────────────────────────────────────────────────
    'payment_methods_title': 'طرق الدفع',
    'payment_manage_info': 'إدارة بطاقاتك وتفضيلات الدفع',
    'payment_add_fab': 'إضافة',
    'payment_security_title': 'أمان الدفع',
    'payment_security_desc': 'جميع معاملاتك مؤمّنة بتشفير SSL. لا يتم تخزين معلوماتك المصرفية على خوادمنا.',
    'payment_pci_certified': 'معتمد PCI DSS',
    'payment_set_default': 'تعيين كافتراضي',
    'payment_expires': 'تنتهي',
    'payment_add_sheet_title': 'إضافة طريقة دفع',
    'payment_card_option_title': 'بطاقة بنكية',
    'payment_card_option_subtitle': 'إضافة بطاقة Visa أو Mastercard جديدة...',
    'payment_cash_option_title': 'الدفع عند التسليم',
    'payment_cash_option_subtitle': 'تفعيل الدفع عند التسليم',
    'payment_cash_activated': 'تم تفعيل الدفع عند التسليم!',
    'payment_add_card_title': 'إضافة بطاقة بنكية',
    'payment_add_card_content': 'نموذج إضافة البطاقة سيتم تطبيقه مع خدمة الدفع.',
    'payment_edit_coming_soon': 'تعديل طريقة الدفع سيتم تطبيقه قريباً.',
    'payment_add_coming_soon': 'إضافة البطاقة سيتم تطبيقها قريباً.',
    'payment_delete_title': 'حذف طريقة الدفع',
    'payment_delete_confirm': 'هل أنت متأكد من رغبتك في حذف طريقة الدفع هذه؟',
    'payment_deleted_success': 'تم حذف طريقة الدفع',
    'payment_set_default_success': 'تم تعيين طريقة الدفع كافتراضية',
    'payment_cash_description': 'الدفع نقداً أو ببطاقة عند التسليم',

    // ── تعديل الملف الشخصي ────────────────────────────────────────
    'edit_profile_title': 'تعديل الملف الشخصي',
    'edit_profile_first_name': 'الاسم الأول',
    'edit_profile_hint_first_name': 'مثال: أحمد',
    'edit_profile_last_name': 'اللقب',
    'edit_profile_hint_last_name': 'مثال: بن علي',
    'edit_profile_email': 'البريد الإلكتروني',
    'edit_profile_email_readonly': 'لا يمكن تغيير البريد الإلكتروني لأسباب أمنية',
    'edit_profile_phone': 'الهاتف',
    'edit_profile_gender': 'الجنس',
    'edit_profile_saving': 'جاري الحفظ...',
    'edit_profile_save_btn': 'حفظ',
    'edit_profile_success': 'تم تحديث الملف الشخصي بنجاح!',
    'edit_profile_error': 'خطأ في تحديث الملف الشخصي',
    'edit_profile_notif_title': 'تم تحديث الملف الشخصي',
    'edit_profile_notif_body': 'تم حفظ معلوماتك بنجاح',
    'edit_profile_first_name_required': 'يرجى إدخال اسمك الأول',
    'edit_profile_last_name_required': 'يرجى إدخال لقبك',
    'edit_profile_phone_required': 'يرجى إدخال رقم هاتفك',
    'edit_profile_section_personal': 'المعلومات الشخصية',
    'edit_profile_section_contact': 'معلومات الاتصال',
    'photo_change_title':    'تغيير صورة الملف الشخصي',
    'photo_from_gallery':    'اختر من المعرض',
    'photo_from_camera':     'التقط صورة',
    'photo_remove':          'حذف الصورة',
    'photo_upload_success':  'تم تحديث صورة الملف الشخصي!',
    'photo_upload_error':    'خطأ في رفع الصورة',
    'photo_removed_success': 'تم حذف صورة الملف الشخصي',

    // ── الأمان ────────────────────────────────────────────────────
    'security_title': 'الأمان',
    'section_confidentiality': 'الخصوصية',
    'section_session': 'الجلسة',
    'security_subtitle': 'إدارة أمان حسابك',
    'security_google_account': 'حساب Google',
    'security_google_connected': 'حسابك مرتبط عبر Google',
    'security_google_how_to': 'كيفية تغيير كلمة المرور؟',
    'security_google_step1': 'اذهب إلى حساب Google الخاص بك',
    'security_google_step2': 'انقر على "الأمان"',
    'security_google_step3': 'تحت "تسجيل الدخول إلى Google"، انقر على "كلمة المرور"',
    'security_google_step4': 'اتبع التعليمات لتغيير كلمة المرور',
    'security_google_warning': 'يجب إجراء تغيير كلمة المرور مباشرة على Google لأسباب أمنية.',
    'security_open_google': 'فتح أمان Google',
    'security_google_dialog_title': 'فتح أمان Google',
    'security_google_dialog_step1': '1. انسخ الرابط أدناه',
    'security_google_dialog_step2': '2. افتح متصفحك',
    'security_google_dialog_step3': '3. الصق الرابط وادخل إلى الصفحة',
    'security_link_copied': 'تم نسخ الرابط!',
    'security_unsupported_title': 'طريقة تسجيل الدخول غير مدعومة',
    'security_unsupported_desc': 'طريقة تسجيل الدخول الحالية لا تسمح بتغيير كلمة المرور من هذا التطبيق.',
    'security_auth_section': 'المصادقة',
    'security_two_factor_subtitle': 'يضيف طبقة أمان إضافية',
    'security_biometric_subtitle': 'استخدم بصمتك أو وجهك',
    'security_change_password_subtitle': 'قم بتحديث كلمة المرور',
    'security_session_section': 'الجلسة',
    'security_auto_logout_title': 'تسجيل الخروج التلقائي',
    'security_auto_logout_subtitle': 'تسجيل الخروج بعد عدم النشاط',
    'security_inactivity_delay': 'مهلة عدم النشاط',
    'security_inactivity_subtitle': 'الوقت قبل تسجيل الخروج التلقائي',
    'security_active_sessions_subtitle': 'إدارة اتصالاتك النشطة',
    'security_privacy_section': 'الخصوصية',
    'security_login_notif_title': 'إشعارات تسجيل الدخول',
    'security_login_notif_subtitle': 'احصل على إشعار عند تسجيل دخول جديد',
    'security_download_data': 'تنزيل بياناتك',
    'security_download_subtitle': 'تصدير معلوماتك الشخصية',
    'security_download_preparing': 'جاري إعداد التنزيل...',
    'security_download_success': 'تم تصدير البيانات بنجاح!',
    'security_download_confirm_title': 'تنزيل بياناتك',
    'security_download_confirm_body': 'هل تريد تنزيل جميع معلوماتك الشخصية؟',
    'security_download_btn': 'تنزيل',
    'security_share_btn': 'مشاركة',
    'security_delete_account': 'حذف الحساب',
    'security_delete_account_subtitle': 'حذف حسابك نهائياً',
    'security_delete_account_confirm': 'هل أنت متأكد من رغبتك في حذف حسابك؟ هذا الإجراء لا رجعة فيه وستُفقد جميع بياناتك.',
    'delete_account_dialog_title': 'حذف حسابي',
    'delete_account_dialog_subtitle': 'سيتم تعطيل حسابك. يمكنك استعادته خلال 30 يومًا عبر بريد إعادة تفعيل الحساب المُرسل إلى عنوان بريدك الإلكتروني.',
    'delete_account_reason_label': 'لماذا تريد حذف حسابك؟',
    'delete_reason_1': 'لم أعد أستخدم التطبيق',
    'delete_reason_2': 'لقد أنشأت حساباً آخر',
    'delete_reason_3': 'التطبيق لا يلبي احتياجاتي',
    'delete_reason_4': 'أنا قلق بشأن خصوصيتي',
    'delete_reason_5': 'أتلقى إشعارات كثيرة جداً',
    'delete_reason_other': 'أخرى (يرجى التحديد)',
    'delete_other_placeholder': 'اكتب سببك هنا...',
    'delete_confirm_instruction': 'لتأكيد الحذف النهائي لحسابك:',
    'delete_confirm_type_label': 'اكتب',
    'delete_confirm_word': 'حذف',
    'delete_account_btn': 'حذف الحساب',
    'account_deactivated_message1': 'تم إلغاء تنشيط حسابك. سيتم حذفه نهائياً خلال 30 يوماً.',
    'security_auto_logout_activated': 'تم تفعيل تسجيل الخروج التلقائي',
    'security_auto_logout_deactivated': 'تم إلغاء تسجيل الخروج التلقائي',
    'security_delay_changed': 'تم تغيير مهلة عدم النشاط إلى',

    // ── التخطيط الرئيسي ───────────────────────────────────────────
    'main_smart_market': 'السوق الذكي',
    'main_purchase_history': 'سجل المشتريات',
    'main_my_profile': 'ملفي الشخصي',
    'main_login_required_title': 'تسجيل الدخول مطلوب',
    'main_login_required_body': 'يجب أن تكون مسجلاً للدخول للوصول إلى هذه الميزة.',
    'main_later': 'لاحقاً',
    'main_cart_summary': 'ملخص عربة التسوق',
    'main_selected_items': 'المنتجات المحددة',
    'main_start_shopping': 'ابدأ التسوق',
    'main_add_to_cart': 'أضف منتجات لبدء التسوق',

    // ── صفحة الإشعارات ───────────────────────────────────────────
    'notif_page_mark_all_read': 'تحديد الكل كمقروء',
    'notif_page_delete_all': 'حذف الكل',
    'notif_page_empty_title': 'لا توجد إشعارات',
    'notif_page_empty_subtitle': 'ليس لديك إشعارات في الوقت الحالي',
    'notif_page_delete_confirm_title': 'حذف الكل',
    'notif_page_delete_confirm_body': 'هل أنت متأكد من رغبتك في حذف جميع إشعاراتك؟',
    'notif_page_time_ago_minutes': 'منذ {n} دقيقة',
    'notif_page_time_ago_hours': 'منذ {n} ساعة',
    'notif_page_time_ago_days': 'منذ {n} يوم',
    'notif_page_time_ago_default': 'منذ فترة',
    'notif_page_mark_error': 'خطأ في تحديد الإشعار',
    'notif_page_delete_error': 'خطأ في حذف الإشعار',

    // ── الجلسات النشطة ────────────────────────────────────────────
    'session_cannot_revoke_current': 'لا يمكن إلغاء الجلسة الحالية',
    'session_revoke_title': 'إلغاء الجلسة',
    'session_revoke_confirm': 'هل أنت متأكد من رغبتك في إلغاء الجلسة على',
    'session_reconnect_required': 'سيحتاج المستخدم إلى تسجيل الدخول مرة أخرى.',
    'session_revoked_success': 'تم إلغاء الجلسة بنجاح',
    'session_revoke_error': 'خطأ في إلغاء الجلسة',
    'session_no_other': 'لا توجد جلسات أخرى للإلغاء',
    'session_revoke_all_title': 'إلغاء جميع الجلسات الأخرى',
    'session_revoke_all_confirm': 'هل أنت متأكد من رغبتك في إلغاء',
    'session_sessions': 'جلسة/جلسات',
    'session_all_reconnect': 'سيحتاج جميع المستخدمين إلى تسجيل الدخول مرة أخرى.',
    'session_revoked_count': 'جلسة/جلسات تم إلغاؤها',
    'session_delete_all_title': 'حذف جميع الجلسات',
    'session_delete_all_confirm': 'تحذير! سيتم حذف جميع جلساتك بما في ذلك الجلسة الحالية.\n\nستحتاج إلى تسجيل الدخول مرة أخرى على جميع أجهزتك.\n\nهل تريد المتابعة؟',
    'session_all_deleted': 'تم حذف جميع الجلسات',
    'session_delete_error': 'خطأ في حذف الجلسات',
    'session_revoke_btn': 'إلغاء',
    'session_current': 'الجلسة الحالية',
    'session_active': 'نشطة',
    'session_inactive': 'غير نشطة',
    'session_version': 'الإصدار',
    'session_last_activity': 'آخر نشاط',
    'session_created_at': 'تم الإنشاء في',
    'session_long_inactive': 'الجلسة غير نشطة منذ فترة طويلة',
    'session_revoke_tooltip': 'إلغاء هذه الجلسة',
    'session_all_sessions': 'جميع الجلسات',
    'session_refresh': 'تحديث الجلسات',
    'session_revoke_all_btn': 'إلغاء الكل',
    'session_none': 'لا توجد جلسات',
    'session_none_desc': 'ستظهر الجلسات هنا عند تسجيل دخولك.',
    'session_total_count': 'جلسة/جلسات إجمالية',
    'session_active_count': 'نشطة',
    'session_inactive_count': 'غير نشطة',
    'session_delete_all_btn': 'حذف الكل',

    // ── نموذج العنوان (ويدجت) ─────────────────────────────────────
    'addr_country_region': 'البلد/المنطقة',
    'addr_personal_info_section': 'المعلومات الشخصية',
    'addr_contact_name_hint': 'اسم جهة الاتصال*',
    'addr_contact_name_helper': 'يرجى إدخال اسم جهة الاتصال.',
    'addr_contact_name_error': 'يرجى إدخال اسم جهة الاتصال',
    'addr_phone_hint': 'رقم الجوال*',
    'addr_phone_error_required': 'الرقم مطلوب',
    'addr_phone_error_invalid': 'رقم غير صحيح',
    'addr_address_section': 'العنوان',
    'addr_street_hint': 'الشارع ورقم الشارع*',
    'addr_street_error': 'الشارع مطلوب',
    'addr_complement_hint': 'شقة، جناح، وحدة، إلخ. (اختياري)',
    'addr_province_hint': 'المحافظة*',
    'addr_province_error': 'المحافظة مطلوبة',
    'addr_city_hint': 'المدينة*',
    'addr_city_error': 'المدينة مطلوبة',
    'addr_postal_hint': 'الرمز البريدي*',
    'addr_postal_error': 'الرمز البريدي مطلوب',

    // ── حوار تسجيل الخروج التلقائي ───────────────────────────────
    'autologout_title': 'تسجيل الخروج\nالتلقائي',
    'autologout_will_logout': 'سيتم تسجيل خروجك خلال',
    'autologout_second': 'ثانية',
    'autologout_seconds': 'ثوانٍ',
    'autologout_inactivity_msg': 'لقد كنت غير نشط لفترة طويلة. انقر أدناه للبقاء متصلاً.',
    'autologout_stay': 'البقاء متصلاً',
    'autologout_logout': 'تسجيل الخروج',

    // ── ويدجت الجنس ──────────────────────────────────────────────
    'gender_select_placeholder': 'اختر الجنس',
    'gender_dialog_title': 'اختر الجنس',

    // ── ويدجت الهاتف ─────────────────────────────────────────────
    'phone_select_country': 'اختر دولة',
    'phone_search_country': 'ابحث عن دولة...',
    'phone_label': 'الهاتف',

    // ── ويدجت الصورة الشخصية ───────────────────────────────────────────────
    'change_photo': 'تغيير الصورة',
    'choose_photo': 'اختر صورة',
    'camera': 'الكاميرا',
    'gallery': 'المعرض',

    // ── ويدجت عنصر الأسئلة الشائعة ───────────────────────────────────────────────
    'faq_question': 'سؤال',
    'faq_category': 'الفئة',
    'faq_content_unavailable': 'المحتوى غير متاح',
    'faq_useful': 'مفيد',
    'faq_share': 'مشاركة',

    // ── شاشة البداية ───────────────────────────────────────────────────
    'splash_loading': 'جاري التحميل',
    'splash_version': 'الإصدار 1.0.0',
    'splash_copyright': '© 2026 winzy. جميع الحقوق محفوظة.',

    // ── Change Password Page ───────────────────────────────────
    'change_password_google_title': 'فتح أمان Google',
    'change_password_google_desc': 'لتغيير كلمة مرور Google، يرجى:',
    'change_password_google_step1': '1. انسخ الرابط أدناه',
    'change_password_google_step2': '2. افتح متصفحك',
    'change_password_google_step3': '3. الصق الرابط وادخل إلى الصفحة',
    'change_password_link_copied': 'تم نسخ الرابط!',
    'change_password_google_account': 'حساب Google',
    'change_password_google_connected': 'حسابك مرتبط عبر Google',
    'change_password_how_to': 'كيفية تغيير كلمة المرور؟',
    'change_password_google_step1_1': '1. اذهب إلى حساب Google الخاص بك',
    'change_password_google_step2_1': '2. انقر على "الأمان"',
    'change_password_google_step3_1': '3. تحت "تسجيل الدخول إلى Google"، انقر على "كلمة المرور"',
    'change_password_google_step4_1': '4. اتبع التعليمات لتغيير كلمة المرور',
    'change_password_google_warning': 'يجب إجراء تغيير كلمة المرور مباشرة على Google لأسباب أمنية.',
    'change_password_info_secure': 'معلوماتك مشفرة وآمنة',

    // ── Session Timeout Values ───────────────────────────────────────
    'session_timeout_5_seconds': '5 ثوانٍ',
    'session_timeout_15_minutes': '15 دقيقة',
    'session_timeout_30_minutes': '30 دقيقة',
    'session_timeout_1_hour': '1 ساعة',
    'session_timeout_2_hours': 'ساعتان',

    // ── ويدجت تبديل العنوان الافتراضي ─────────────────────────────────────────────
    'set_default_address': 'تعيين كعنوان شحن افتراضي',


    'payment_card_number_label':       'رقم البطاقة',
    'payment_cardholder_label':        'اسم حامل البطاقة',
    'payment_cardholder_hint':         'الاسم الأول واسم العائلة',
    'payment_cardholder_required':     'اسم حامل البطاقة مطلوب',
    'payment_expiry_label':            'تاريخ الانتهاء',
    'payment_expiry_required':         'تاريخ الانتهاء مطلوب',
    'payment_expiry_invalid':          'صيغة غير صالحة',
    'payment_card_expired':            'البطاقة منتهية الصلاحية',
    'payment_cvv_label':               'رمز CVV',
    'payment_cvv_invalid':             'رمز CVV غير صالح',
    'payment_card_number_invalid':     'رقم البطاقة غير صالح',
    'payment_card_holder_label_preview': 'حامل البطاقة',
    'payment_card_holder_placeholder': 'اسمك',
    'payment_expires_preview':         'تنتهي',
    'payment_add_card_btn':            'إضافة البطاقة',
    'payment_card_added_success':      'تمت إضافة البطاقة بنجاح!',
    'payment_paypal_option_title':    'PayPal',
    'payment_paypal_option_subtitle': 'الدفع عبر حساب PayPal الخاص بك',
    'payment_paypal_add_success':    'تمت إضافة حساب PayPal بنجاح!',
    'payment_paypal_add_error':      'خطأ في إضافة حساب PayPal',
    'payment_paypal_email_required':  'البريد الإلكتروني لـ PayPal مطلوب',
    'payment_paypal_email_invalid':   'يرجى إدخال بريد إلكتروني صحيح لـ PayPal',
    'payment_paypal_name_required':   'اسم صاحب الحساب مطلوب',
    'payment_paypal_terms_required': 'يجب قبول شروط الاستخدام',
    'payment_applepay_option_title':  'Apple Pay / Google Pay',
    'payment_applepay_option_subtitle': 'دفع سريع عبر هاتفك',
    'payment_coming_soon':            'قريباً',
    'payment_cash_delivery_title': 'الدفع عند الاستلام',
    'payment_cash_delivery_desc':  'ادفع نقداً عند استلام طلبك',

    // ══════════════════════ paypal ════════════════════════════
    'paypal_page_title':       'ربط PayPal',
    'paypal_header_subtitle':  'ادفع بأمان باستخدام حساب PayPal الخاص بك',
    'paypal_email_label':      'البريد الإلكتروني لحساب PayPal',
    'paypal_email_hint':       'مثال@paypal.com',
    'paypal_email_required':   'البريد الإلكتروني لـ PayPal مطلوب',
    'paypal_email_invalid':    'عنوان البريد الإلكتروني غير صالح',
    'paypal_info_text':        'أدخل عنوان البريد الإلكتروني المرتبط بحساب PayPal الخاص بك. بياناتك محمية ومشفرة.',
    'paypal_link_btn':         'ربط حساب PayPal الخاص بي',
    'paypal_no_account':       'ليس لديك حساب PayPal؟',
    'paypal_added_success':    'تم ربط حساب PayPal بنجاح!',
    'paypal_already_added':    'حساب PayPal مرتبط بالفعل',
    'paypal_holder_label':    'اسم صاحب حساب PayPal',
    'paypal_holder_hint':     'الاسم الأول واسم العائلة',
    'paypal_holder_required': 'اسم صاحب الحساب مطلوب',

  };

  // ════════════════════════════════════════════════════════════════
  //  API
  // ════════════════════════════════════════════════════════════════
  static String get(String key, {String? languageCode}) {
    final lang = languageCode ?? _currentLanguageCode;
    return _getTranslations(lang)[key] ?? key;
  }

  static Map<String, String> getAll({String? languageCode}) =>
      _getTranslations(languageCode ?? _currentLanguageCode);

  static Map<String, String> _getTranslations(String languageCode) {
    switch (languageCode) {
      case 'fr':
        return _fr;
      case 'en':
        return _en;
      case 'ar':
        return _ar;
      default:
        return _fr;
    }
  }

  static String _currentLanguageCode = 'fr';
  static void setLanguage(String languageCode) =>
      _currentLanguageCode = languageCode;
  static String getLanguage() => _currentLanguageCode;
  static bool get isRtl => _currentLanguageCode == 'ar';
}

extension AppStrings on String {
  String tr({String? languageCode}) =>
      AppLocalizations.get(this, languageCode: languageCode);
}