class AppLocalizations {
  static final AppLocalizations _instance = AppLocalizations._internal();
  factory AppLocalizations() => _instance;
  AppLocalizations._internal();

  // ════════════════════════════════════════════════════════════════
  //  FRANÇAIS
  // ════════════════════════════════════════════════════════════════
  static const Map<String, String> _fr = {
    'login_title': 'Connexion',
    'signup_title': 'S\'inscrire',
    'email': 'Email',
    'password': 'Mot de passe',
    'email_required': 'Veuillez entrer votre email',
    'password_required': 'Veuillez entrer votre mot de passe',
    'invalid_email': 'Veuillez entrer un email valide',
    'logout': 'Déconnexion',
    'confirm_logout': 'Êtes-vous sûr de vouloir vous déconnecter ?',
    'login': 'Se connecter',
    'logging_in': 'Connexion en cours...',
    'continue_google': 'Continuer avec Google',
    'continue_guest': 'Continuer comme visiteur',
    'no_account': 'Pas de compte ?',
    'already_account': 'Déjà un compte ?',
    'forgot_password': 'Mot de passe oublié ?',
    'remember_me': 'Se souvenir de moi',
    'create_account': 'Créer un compte',
    'confirm_password': 'Confirmer le mot de passe',
    'confirm_password_required': 'Veuillez confirmer votre mot de passe',
    'passwords_not_match': 'Les mots de passe ne correspondent pas',
    'password_min_length': 'Au moins 8 caractères',
    'password_uppercase': 'Au moins une lettre majuscule',
    'password_lowercase': 'Au moins une lettre minuscule',
    'password_requirements': 'Le mot de passe ne respecte pas les conditions',
    'password_must_contain': 'Le mot de passe doit contenir :',
    'profile_complete_later': 'Les autres informations seront à compléter dans votre profil.',
    'agree_terms': 'J\'accepte les conditions générales d\'utilisation',
    'accept_terms_required': 'Veuillez accepter les conditions générales',
    'signup_success': 'Compte créé avec succès !',
    'verification_email_sent': 'Un email de vérification a été envoyé à :',
    'verify_before_login': 'Veuillez vérifier votre boîte de réception et cliquer sur le lien avant de vous connecter.',
    'understand': 'OK, j\'ai compris',
    'signing_up': 'Inscription en cours...',
    'terms_conditions': 'Conditions Générales d\'Utilisation',
    'close': 'Fermer',
    'i_agree': 'J\'accepte',
    'forgot_password_title': 'MOT DE PASSE OUBLIÉ',
    'forgot_password_desc': 'Entrez votre adresse email pour recevoir\nun lien de réinitialisation',
    'send_link': 'Envoyer le lien',
    'sending': 'Envoi en cours...',
    'back_to': 'Retourner à la',
    'login_page': 'page de connexion',
    'email_sent': 'Email envoyé !',
    'reset_link_sent': 'Un lien de réinitialisation a été envoyé à',
    'check_inbox_reset': 'Vérifiez votre boîte de réception et cliquez sur le lien pour réinitialiser votre mot de passe',
    'continue': 'Continuer',
    'home': 'Accueil',
    'cart': 'Panier',
    'history': 'Historique',
    'profile': 'Profil',
    'settings': 'Paramètres',
    'personal_info': 'Informations personnelles',
    'addresses': 'Adresses',
    'payment_methods': 'Méthodes de paiement',
    'notification_settings': 'Paramètres de notification',
    'security': 'Sécurité',
    'language': 'Langue',
    'help': 'Aide',
    'orders': 'Commandes',
    'favorites': 'Favoris',
    'points': 'Points',
    'change_password': 'Changer le mot de passe',
    'current_password': 'Mot de passe actuel',
    'new_password': 'Nouveau mot de passe',
    'confirm_password_field': 'Confirmer le mot de passe',
    'two_factor_auth': 'Authentification à deux facteurs',
    'biometric_auth': 'Authentification biométrique',
    'active_sessions': 'Sessions actives',
    'payment': 'Paiement',
    'order_summary': 'Résumé de la commande',
    'delivery_address': 'Adresse de livraison',
    'payment_method': 'Méthode de paiement',
    'subtotal': 'Sous-total',
    'shipping': 'Livraison',
    'discount': 'Réduction',
    'total': 'Total',
    'pay': 'Payer',
    'credit_card': 'Carte bancaire',
    'paypal': 'PayPal',
    'apple_pay': 'Apple Pay',
    'session_warning': 'Avertissement de session',
    'inactivity_warning': 'Vous allez être déconnecté en raison de l\'inactivité',
    'stay_logged_in': 'Rester connecté',
    'session_expired': 'Votre session a expiré',
    'inactivity_detected': 'Inactivité détectée',
    'remaining_time': 'Temps restant',
    'success': 'Succès',
    'error': 'Erreur',
    'loading': 'Chargement...',
    'no_data': 'Aucune donnée',
    'save': 'Enregistrer',
    'edit': 'Modifier',
    'delete': 'Supprimer',
    'confirm': 'Confirmer',
    'cancel': 'Annuler',
    'back': 'Retour',
    'ok': 'OK',
    'add': 'Ajouter',
    'by_default': 'Par défaut',

    // ── Panier ────────────────────────────────────────────────────
    'cart_title': 'Panier',
    'select_all': 'Tout',
    'summary': 'Résumé',
    'article': 'article',
    'articles': 'articles',
    'reductions': 'Réductions',
    'estimated_total': 'Total estimé',
    'checkout': 'Commander',
    'empty_cart': 'Votre panier est vide',
    'item_removed': 'Article supprimé',
    'quantity': 'Quantité',
    'items_selected': 'articles sélectionnés',

    // ── Adresses ──────────────────────────────────────────────────
    'delivery_address_title': 'Adresse de livraison',
    'add_new_address': 'Ajouter une nouvelle adresse',
    'add_address_title': 'Ajouter une nouvelle adresse',
    'edit_address_title': 'Modifier l\'adresse',
    'default_address': 'Adresse par défaut',
    'set_as_default': 'Par défaut',
    'no_addresses': 'Aucune adresse',
    'add_first_address': 'Ajoutez votre première adresse de livraison',
    'loading_addresses': 'Chargement des adresses...',
    'delete_address': 'Supprimer l\'adresse',
    'confirm_delete_address': 'Êtes-vous sûr de vouloir\nsupprimer cette adresse ?',
    'address_saved': 'Adresse enregistrée avec succès !',
    'address_updated': 'Adresse mise à jour avec succès !',
    'address_default_updated': 'Votre adresse par défaut a été mise à jour',
    'address_default_title': 'Adresse par défaut',
    'address_load_error': 'Erreur lors du chargement des adresses',
    'new_badge': 'Nouveau !',
    'all_info_encrypted': 'Toutes vos informations sont cryptées',
    'info_encrypted_secure': 'Vos informations sont cryptées et sécurisées',
    'update_address_info': 'Mettez à jour vos informations d\'adresse',

    // ── Formulaire d'adresse ──────────────────────────────────────
    'section_contact_info': 'Informations de contact',
    'section_address_info': 'Informations d\'adresse',
    'contact_name': 'Nom du contact',
    'contact_name_required': 'Veuillez entrer un nom de contact',
    'hint_contact_name': 'Ex : Jean Dupont',
    'phone': 'Téléphone',
    'phone_required': 'Veuillez entrer un numéro de téléphone',
    'hint_phone': 'Ex : 20 123 456',
    'street': 'Rue / Adresse',
    'street_required': 'Veuillez entrer une adresse',
    'hint_street': 'Ex : 12 rue de la République',
    'complement': 'Complément d\'adresse',
    'hint_complement': 'Ex : Appartement 4B, Bâtiment C',
    'province': 'Province / État',
    'province_required': 'Veuillez entrer une province',
    'hint_province': 'Ex : Tunis',
    'city': 'Ville',
    'city_required': 'Veuillez entrer une ville',
    'hint_city': 'Ex : Tunis',
    'postal_code': 'Code postal',
    'postal_code_required': 'Veuillez entrer un code postal',
    'hint_postal_code': 'Ex : 1000',
    'country': 'Pays',
    'search_country': 'Rechercher un pays...',
    'save_address_btn': 'Enregistrer l\'adresse',
    'saving_address_btn': 'Enregistrement...',
    'update_address_btn': 'Mettre à jour l\'adresse',
    'updating_address_btn': 'Mise à jour...',
    'set_default_label': 'Définir comme adresse par défaut',
    'set_default_description': 'Cette adresse sera utilisée automatiquement lors de vos commandes',

    // ── Centre d'aide ─────────────────────────────────────────────
    'help_center_title': 'Centre d\'aide',
    'help_search_hint': 'Rechercher une aide...',
    'help_category_all': 'Tous',
    'help_empty_title': 'Aucune aide trouvée',
    'help_empty_subtitle': 'Essayez de modifier votre recherche ou de changer de catégorie',
    'help_faq_content_unavailable': 'Contenu non disponible',
    'help_faq_load_error': 'Erreur lors du chargement des FAQs',
    'help_support_fab': 'Support',
    'help_contact_title': 'Contacter le support',
    'help_chat_title': 'Chat en direct',
    'help_chat_subtitle': 'Discutez avec un agent maintenant',
    'help_chat_soon': 'Chat en direct bientôt disponible !',
    'help_phone_title': 'Téléphone',
    'help_phone_subtitle': 'Appelez-nous au +216 70 000 000',
    'help_phone_unavailable': 'Application téléphonique non disponible sur cet appareil',
    'help_email_title': 'Email',
    'help_email_subtitle': 'Envoyez-nous un email à support@winzy.com',
    'help_email_copied': 'Email copié dans le presse-papiers !',
    'help_email_fallback': 'Email : support@winzy.com',
    'help_category_commandes': 'Commandes',
    'help_category_paiement': 'Paiement',
    'help_category_compte': 'Compte',
    'help_category_livraison': 'Livraison',
    'help_category_retours': 'Retours',
    'help_category_securite': 'Sécurité',
    'help_category_application': 'Application',

    // ── Paramètres de notification ────────────────────────────────
    'notif_settings_title': 'Paramètres de notification',
    'notif_save_tooltip': 'Enregistrer les paramètres',
    'notif_saved_success': 'Paramètres enregistrés avec succès !',
    'notif_section_general': 'Notifications générales',
    'notif_push_title': 'Notifications push',
    'notif_push_subtitle': 'Recevoir des notifications sur votre appareil',
    'notif_email_title': 'Notifications par email',
    'notif_email_subtitle': 'Recevoir des notifications par email',
    'notif_section_orders': 'Commandes et livraisons',
    'notif_orders_title': 'Mises à jour de commande',
    'notif_orders_subtitle': 'Suivi de votre commande et livraison',
    'notif_section_marketing': 'Marketing et promotions',
    'notif_promo_title': 'Offres promotionnelles',
    'notif_promo_subtitle': 'Réductions et offres spéciales',
    'notif_new_products_title': 'Nouveaux produits',
    'notif_new_products_subtitle': 'Découvrez les nouveaux arrivages',
    'notif_price_drops_title': 'Baisse de prix',
    'notif_price_drops_subtitle': 'Alertes lorsque les prix baissent',
    'notif_newsletter_title': 'Newsletter',
    'notif_newsletter_subtitle': 'Actualités et conseils hebdomadaires',
    'notif_section_account': 'Compte et sécurité',
    'notif_account_title': 'Mises à jour du compte',
    'notif_account_subtitle': 'Changements importants sur votre compte',
    'notif_security_title': 'Alertes de sécurité',
    'notif_security_subtitle': 'Activités suspectes et connexions',

    // ── Moyens de paiement ────────────────────────────────────────
    'payment_methods_title': 'Moyens de paiement',
    'payment_manage_info': 'Gérez vos cartes et préférences de paiement',
    'payment_add_fab': 'Ajouter',
    'payment_security_title': 'Sécurité des paiements',
    'payment_security_desc': 'Toutes vos transactions sont sécurisées avec le cryptage SSL. Vos informations bancaires ne sont jamais stockées sur nos serveurs.',
    'payment_pci_certified': 'Certifié PCI DSS',
    'payment_set_default': 'Définir par défaut',
    'payment_expires': 'Expire',
    'payment_add_sheet_title': 'Ajouter un moyen de paiement',
    'payment_card_option_title': 'Carte bancaire',
    'payment_card_option_subtitle': 'Ajouter une nouvelle carte Visa, Mastercard...',
    'payment_cash_option_title': 'Paiement à la livraison',
    'payment_cash_option_subtitle': 'Activer le paiement lors de la livraison',
    'payment_cash_activated': 'Paiement à la livraison activé !',
    'payment_add_card_title': 'Ajouter une carte bancaire',
    'payment_add_card_content': 'Formulaire d\'ajout de carte à implémenter avec un service de paiement.',
    'payment_edit_coming_soon': 'Modification du moyen de paiement à implémenter.',
    'payment_add_coming_soon': 'Ajout de carte à implémenter.',
    'payment_delete_title': 'Supprimer le moyen de paiement',
    'payment_delete_confirm': 'Êtes-vous sûr de vouloir supprimer ce moyen de paiement ?',
    'payment_deleted_success': 'Moyen de paiement supprimé',
    'payment_set_default_success': 'Moyen de paiement défini par défaut',
    'payment_cash_description': 'Payer en espèces ou par carte lors de la livraison',

    // ── Modifier le profil ────────────────────────────────────────
    'edit_profile_title': 'Modifier le profil',
    'edit_profile_first_name': 'Prénom',
    'edit_profile_hint_first_name': 'Ex : Jean',
    'edit_profile_last_name': 'Nom',
    'edit_profile_hint_last_name': 'Ex : Dupont',
    'edit_profile_email': 'Email',
    'edit_profile_email_readonly': 'Email non modifiable pour des raisons de sécurité',
    'edit_profile_phone': 'Téléphone',
    'edit_profile_gender': 'Genre',
    'edit_profile_saving': 'Sauvegarde...',
    'edit_profile_save_btn': 'Sauvegarder',
    'edit_profile_success': 'Profil mis à jour avec succès !',
    'edit_profile_error': 'Erreur lors de la mise à jour du profil',
    'edit_profile_notif_title': 'Profil mis à jour',
    'edit_profile_notif_body': 'Vos informations ont été enregistrées avec succès',
    'edit_profile_first_name_required': 'Veuillez entrer votre prénom',
    'edit_profile_last_name_required': 'Veuillez entrer votre nom',
    'edit_profile_phone_required': 'Veuillez entrer votre numéro de téléphone',
    'edit_profile_section_personal': 'Informations personnelles',
    'edit_profile_section_contact': 'Contact',
  };

  // ════════════════════════════════════════════════════════════════
  //  ENGLISH
  // ════════════════════════════════════════════════════════════════
  static const Map<String, String> _en = {
    'login_title': 'Login',
    'signup_title': 'Sign Up',
    'email': 'Email',
    'password': 'Password',
    'email_required': 'Please enter your email',
    'password_required': 'Please enter your password',
    'invalid_email': 'Please enter a valid email',
    'logout': 'Logout',
    'confirm_logout': 'Are you sure you want to logout?',
    'login': 'Sign In',
    'logging_in': 'Signing in...',
    'continue_google': 'Continue with Google',
    'continue_guest': 'Continue as Guest',
    'no_account': 'Don\'t have an account?',
    'already_account': 'Already have an account?',
    'forgot_password': 'Forgot password?',
    'remember_me': 'Remember me',
    'create_account': 'Create an Account',
    'confirm_password': 'Confirm Password',
    'confirm_password_required': 'Please confirm your password',
    'passwords_not_match': 'Passwords do not match',
    'password_min_length': 'At least 8 characters',
    'password_uppercase': 'At least one uppercase letter',
    'password_lowercase': 'At least one lowercase letter',
    'password_requirements': 'Password does not meet requirements',
    'password_must_contain': 'Password must contain:',
    'profile_complete_later': 'Other information will be completed in your profile later.',
    'agree_terms': 'I agree to the terms and conditions',
    'accept_terms_required': 'Please accept the terms and conditions',
    'signup_success': 'Account created successfully!',
    'verification_email_sent': 'A verification email has been sent to:',
    'verify_before_login': 'Please check your inbox and click the verification link before logging in.',
    'understand': 'OK, I understand',
    'signing_up': 'Signing up...',
    'terms_conditions': 'Terms and Conditions',
    'close': 'Close',
    'i_agree': 'I Agree',
    'forgot_password_title': 'FORGOT PASSWORD',
    'forgot_password_desc': 'Enter your email address to receive\na password reset link',
    'send_link': 'Send Link',
    'sending': 'Sending...',
    'back_to': 'Back to',
    'login_page': 'login page',
    'email_sent': 'Email Sent!',
    'reset_link_sent': 'A reset link has been sent to',
    'check_inbox_reset': 'Check your inbox and click the link to reset your password',
    'continue': 'Continue',
    'home': 'Home',
    'cart': 'Cart',
    'history': 'History',
    'profile': 'Profile',
    'settings': 'Settings',
    'personal_info': 'Personal Information',
    'addresses': 'Addresses',
    'payment_methods': 'Payment Methods',
    'notification_settings': 'Notification Settings',
    'security': 'Security',
    'language': 'Language',
    'help': 'Help',
    'orders': 'Orders',
    'favorites': 'Favorites',
    'points': 'Points',
    'change_password': 'Change Password',
    'current_password': 'Current Password',
    'new_password': 'New Password',
    'confirm_password_field': 'Confirm Password',
    'two_factor_auth': 'Two-Factor Authentication',
    'biometric_auth': 'Biometric Authentication',
    'active_sessions': 'Active Sessions',
    'payment': 'Payment',
    'order_summary': 'Order Summary',
    'delivery_address': 'Delivery Address',
    'payment_method': 'Payment Method',
    'subtotal': 'Subtotal',
    'shipping': 'Shipping',
    'discount': 'Discount',
    'total': 'Total',
    'pay': 'Pay',
    'credit_card': 'Credit Card',
    'paypal': 'PayPal',
    'apple_pay': 'Apple Pay',
    'session_warning': 'Session Warning',
    'inactivity_warning': 'You will be logged out due to inactivity',
    'stay_logged_in': 'Stay Logged In',
    'session_expired': 'Your session has expired',
    'inactivity_detected': 'Inactivity Detected',
    'remaining_time': 'Remaining Time',
    'success': 'Success',
    'error': 'Error',
    'loading': 'Loading...',
    'no_data': 'No data',
    'save': 'Save',
    'edit': 'Edit',
    'delete': 'Delete',
    'confirm': 'Confirm',
    'cancel': 'Cancel',
    'back': 'Back',
    'ok': 'OK',
    'add': 'Add',
    'by_default': 'Default',

    // ── Cart ──────────────────────────────────────────────────────
    'cart_title': 'Cart',
    'select_all': 'All',
    'summary': 'Summary',
    'article': 'item',
    'articles': 'items',
    'reductions': 'Discounts',
    'estimated_total': 'Estimated Total',
    'checkout': 'Checkout',
    'empty_cart': 'Your cart is empty',
    'item_removed': 'Item removed',
    'quantity': 'Quantity',
    'items_selected': 'items selected',

    // ── Addresses ─────────────────────────────────────────────────
    'delivery_address_title': 'Delivery Address',
    'add_new_address': 'Add New Address',
    'add_address_title': 'Add New Address',
    'edit_address_title': 'Edit Address',
    'default_address': 'Default Address',
    'set_as_default': 'Default',
    'no_addresses': 'No Addresses',
    'add_first_address': 'Add your first delivery address',
    'loading_addresses': 'Loading addresses...',
    'delete_address': 'Delete Address',
    'confirm_delete_address': 'Are you sure you want to\ndelete this address?',
    'address_saved': 'Address saved successfully!',
    'address_updated': 'Address updated successfully!',
    'address_default_updated': 'Your default address has been updated',
    'address_default_title': 'Default Address',
    'address_load_error': 'Error loading addresses',
    'new_badge': 'New!',
    'all_info_encrypted': 'All your information is encrypted',
    'info_encrypted_secure': 'Your information is encrypted and secure',
    'update_address_info': 'Update your address information',

    // ── Address Form ──────────────────────────────────────────────
    'section_contact_info': 'Contact Information',
    'section_address_info': 'Address Information',
    'contact_name': 'Contact Name',
    'contact_name_required': 'Please enter a contact name',
    'hint_contact_name': 'E.g.: John Doe',
    'phone': 'Phone',
    'phone_required': 'Please enter a phone number',
    'hint_phone': 'E.g.: 20 123 456',
    'street': 'Street / Address',
    'street_required': 'Please enter an address',
    'hint_street': 'E.g.: 12 Main Street',
    'complement': 'Address Complement',
    'hint_complement': 'E.g.: Apartment 4B, Building C',
    'province': 'Province / State',
    'province_required': 'Please enter a province',
    'hint_province': 'E.g.: Tunis',
    'city': 'City',
    'city_required': 'Please enter a city',
    'hint_city': 'E.g.: Tunis',
    'postal_code': 'Postal Code',
    'postal_code_required': 'Please enter a postal code',
    'hint_postal_code': 'E.g.: 1000',
    'country': 'Country',
    'search_country': 'Search country...',
    'save_address_btn': 'Save Address',
    'saving_address_btn': 'Saving...',
    'update_address_btn': 'Update Address',
    'updating_address_btn': 'Updating...',
    'set_default_label': 'Set as default address',
    'set_default_description': 'This address will be used automatically for your orders',

    // ── Help Center ───────────────────────────────────────────────
    'help_center_title': 'Help Center',
    'help_search_hint': 'Search for help...',
    'help_category_all': 'All',
    'help_empty_title': 'No help found',
    'help_empty_subtitle': 'Try modifying your search or changing category',
    'help_faq_content_unavailable': 'Content unavailable',
    'help_faq_load_error': 'Error loading FAQs',
    'help_support_fab': 'Support',
    'help_contact_title': 'Contact Support',
    'help_chat_title': 'Live Chat',
    'help_chat_subtitle': 'Chat with an agent now',
    'help_chat_soon': 'Live chat coming soon!',
    'help_phone_title': 'Phone',
    'help_phone_subtitle': 'Call us at +216 70 000 000',
    'help_phone_unavailable': 'Phone app not available on this device',
    'help_email_title': 'Email',
    'help_email_subtitle': 'Send us an email at support@winzy.com',
    'help_email_copied': 'Email copied to clipboard!',
    'help_email_fallback': 'Email: support@winzy.com',
    'help_category_commandes': 'Orders',
    'help_category_paiement': 'Payment',
    'help_category_compte': 'Account',
    'help_category_livraison': 'Delivery',
    'help_category_retours': 'Returns',
    'help_category_securite': 'Security',
    'help_category_application': 'App',

    // ── Notification Settings ─────────────────────────────────────
    'notif_settings_title': 'Notification Settings',
    'notif_save_tooltip': 'Save settings',
    'notif_saved_success': 'Settings saved successfully!',
    'notif_section_general': 'General Notifications',
    'notif_push_title': 'Push Notifications',
    'notif_push_subtitle': 'Receive notifications on your device',
    'notif_email_title': 'Email Notifications',
    'notif_email_subtitle': 'Receive notifications by email',
    'notif_section_orders': 'Orders & Deliveries',
    'notif_orders_title': 'Order Updates',
    'notif_orders_subtitle': 'Track your order and delivery',
    'notif_section_marketing': 'Marketing & Promotions',
    'notif_promo_title': 'Promotional Offers',
    'notif_promo_subtitle': 'Discounts and special deals',
    'notif_new_products_title': 'New Products',
    'notif_new_products_subtitle': 'Discover new arrivals',
    'notif_price_drops_title': 'Price Drops',
    'notif_price_drops_subtitle': 'Alerts when prices decrease',
    'notif_newsletter_title': 'Newsletter',
    'notif_newsletter_subtitle': 'Weekly news and tips',
    'notif_section_account': 'Account & Security',
    'notif_account_title': 'Account Updates',
    'notif_account_subtitle': 'Important changes to your account',
    'notif_security_title': 'Security Alerts',
    'notif_security_subtitle': 'Suspicious activity and logins',

    // ── Payment Methods ───────────────────────────────────────────
    'payment_methods_title': 'Payment Methods',
    'payment_manage_info': 'Manage your cards and payment preferences',
    'payment_add_fab': 'Add',
    'payment_security_title': 'Payment Security',
    'payment_security_desc': 'All your transactions are secured with SSL encryption. Your banking information is never stored on our servers.',
    'payment_pci_certified': 'PCI DSS Certified',
    'payment_set_default': 'Set as default',
    'payment_expires': 'Expires',
    'payment_add_sheet_title': 'Add Payment Method',
    'payment_card_option_title': 'Credit Card',
    'payment_card_option_subtitle': 'Add a new Visa, Mastercard...',
    'payment_cash_option_title': 'Cash on Delivery',
    'payment_cash_option_subtitle': 'Enable payment on delivery',
    'payment_cash_activated': 'Cash on delivery activated!',
    'payment_add_card_title': 'Add Credit Card',
    'payment_add_card_content': 'Card form to be implemented with a payment service.',
    'payment_edit_coming_soon': 'Payment method modification to be implemented.',
    'payment_add_coming_soon': 'Card addition to be implemented.',
    'payment_delete_title': 'Delete Payment Method',
    'payment_delete_confirm': 'Are you sure you want to delete this payment method?',
    'payment_deleted_success': 'Payment method deleted',
    'payment_set_default_success': 'Payment method set as default',
    'payment_cash_description': 'Pay in cash or by card upon delivery',

    // ── Edit Profile ──────────────────────────────────────────────
    'edit_profile_title': 'Edit Profile',
    'edit_profile_first_name': 'First Name',
    'edit_profile_hint_first_name': 'E.g.: John',
    'edit_profile_last_name': 'Last Name',
    'edit_profile_hint_last_name': 'E.g.: Doe',
    'edit_profile_email': 'Email',
    'edit_profile_email_readonly': 'Email cannot be changed for security reasons',
    'edit_profile_phone': 'Phone',
    'edit_profile_gender': 'Gender',
    'edit_profile_saving': 'Saving...',
    'edit_profile_save_btn': 'Save',
    'edit_profile_success': 'Profile updated successfully!',
    'edit_profile_error': 'Error updating profile',
    'edit_profile_notif_title': 'Profile updated',
    'edit_profile_notif_body': 'Your information has been saved successfully',
    'edit_profile_first_name_required': 'Please enter your first name',
    'edit_profile_last_name_required': 'Please enter your last name',
    'edit_profile_phone_required': 'Please enter your phone number',
    'edit_profile_section_personal': 'Personal Information',
    'edit_profile_section_contact': 'Contact',
  };

  // ════════════════════════════════════════════════════════════════
  //  ARABIC
  // ════════════════════════════════════════════════════════════════
  static const Map<String, String> _ar = {
    'login_title': 'تسجيل الدخول',
    'signup_title': 'التسجيل',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'email_required': 'يرجى إدخال بريدك الإلكتروني',
    'password_required': 'يرجى إدخال كلمة المرور',
    'invalid_email': 'يرجى إدخال بريد إلكتروني صحيح',
    'logout': 'تسجيل الخروج',
    'confirm_logout': 'هل أنت متأكد من رغبتك في تسجيل الخروج؟',
    'login': 'تسجيل الدخول',
    'logging_in': 'جاري تسجيل الدخول...',
    'continue_google': 'الاستمرار مع Google',
    'continue_guest': 'الاستمرار كضيف',
    'no_account': 'لا تملك حساباً؟',
    'already_account': 'هل لديك حساب بالفعل؟',
    'forgot_password': 'هل نسيت كلمة المرور؟',
    'remember_me': 'تذكرني',
    'create_account': 'إنشاء حساب',
    'confirm_password': 'تأكيد كلمة المرور',
    'confirm_password_required': 'يرجى تأكيد كلمة المرور',
    'passwords_not_match': 'كلمات المرور غير متطابقة',
    'password_min_length': 'على الأقل 8 أحرف',
    'password_uppercase': 'حرف كبير واحد على الأقل',
    'password_lowercase': 'حرف صغير واحد على الأقل',
    'password_requirements': 'كلمة المرور لا تفي بالمتطلبات',
    'password_must_contain': 'يجب أن تحتوي كلمة المرور على:',
    'profile_complete_later': 'سيتم إكمال المعلومات الأخرى في ملفك الشخصي لاحقاً.',
    'agree_terms': 'أوافق على شروط الاستخدام',
    'accept_terms_required': 'يرجى قبول شروط الاستخدام',
    'signup_success': 'تم إنشاء الحساب بنجاح!',
    'verification_email_sent': 'تم إرسال بريد التحقق إلى:',
    'verify_before_login': 'يرجى التحقق من صندوق الوارد والنقر على رابط التحقق قبل تسجيل الدخول.',
    'understand': 'حسناً، فهمت',
    'signing_up': 'جاري التسجيل...',
    'terms_conditions': 'الشروط والأحكام',
    'close': 'إغلاق',
    'i_agree': 'أوافق',
    'forgot_password_title': 'نسيت كلمة المرور',
    'forgot_password_desc': 'أدخل بريدك الإلكتروني لتلقي\nرابط استرجاع كلمة المرور',
    'send_link': 'إرسال الرابط',
    'sending': 'جاري الإرسال...',
    'back_to': 'العودة إلى',
    'login_page': 'صفحة تسجيل الدخول',
    'email_sent': 'تم إرسال البريد!',
    'reset_link_sent': 'تم إرسال رابط الاستعادة إلى',
    'check_inbox_reset': 'تحقق من صندوق الوارد وانقر على الرابط لاستعادة كلمة المرور',
    'continue': 'متابعة',
    'home': 'الرئيسية',
    'cart': 'عربة التسوق',
    'history': 'السجل',
    'profile': 'الملف الشخصي',
    'settings': 'الإعدادات',
    'personal_info': 'المعلومات الشخصية',
    'addresses': 'العناوين',
    'payment_methods': 'طرق الدفع',
    'notification_settings': 'إعدادات الإشعارات',
    'security': 'الأمان',
    'language': 'اللغة',
    'help': 'مساعدة',
    'orders': 'الطلبات',
    'favorites': 'المفضلة',
    'points': 'النقاط',
    'change_password': 'تغيير كلمة المرور',
    'current_password': 'كلمة المرور الحالية',
    'new_password': 'كلمة المرور الجديدة',
    'confirm_password_field': 'تأكيد كلمة المرور',
    'two_factor_auth': 'المصادقة الثنائية',
    'biometric_auth': 'المصادقة البيومترية',
    'active_sessions': 'الجلسات النشطة',
    'payment': 'الدفع',
    'order_summary': 'ملخص الطلب',
    'delivery_address': 'عنوان التسليم',
    'payment_method': 'طريقة الدفع',
    'subtotal': 'المجموع الفرعي',
    'shipping': 'الشحن',
    'discount': 'الخصم',
    'total': 'الإجمالي',
    'pay': 'ادفع',
    'credit_card': 'بطاقة ائتمان',
    'paypal': 'PayPal',
    'apple_pay': 'Apple Pay',
    'session_warning': 'تحذير الجلسة',
    'inactivity_warning': 'سيتم تسجيل خروجك بسبب عدم النشاط',
    'stay_logged_in': 'البقاء متصلاً',
    'session_expired': 'انتهت صلاحية جلستك',
    'inactivity_detected': 'تم اكتشاف عدم النشاط',
    'remaining_time': 'الوقت المتبقي',
    'success': 'نجاح',
    'error': 'خطأ',
    'loading': 'جاري التحميل...',
    'no_data': 'لا توجد بيانات',
    'save': 'حفظ',
    'edit': 'تعديل',
    'delete': 'حذف',
    'confirm': 'تأكيد',
    'cancel': 'إلغاء',
    'back': 'رجوع',
    'ok': 'حسناً',
    'add': 'إضافة',
    'by_default': 'افتراضي',

    // ── عربة التسوق ───────────────────────────────────────────────
    'cart_title': 'عربة التسوق',
    'select_all': 'الكل',
    'summary': 'الملخص',
    'article': 'منتج',
    'articles': 'منتجات',
    'reductions': 'الخصومات',
    'estimated_total': 'الإجمالي المقدر',
    'checkout': 'إتمام الطلب',
    'empty_cart': 'عربة التسوق فارغة',
    'item_removed': 'تم حذف المنتج',
    'quantity': 'الكمية',
    'items_selected': 'منتجات مختارة',

    // ── العناوين ──────────────────────────────────────────────────
    'delivery_address_title': 'عنوان التسليم',
    'add_new_address': 'إضافة عنوان جديد',
    'add_address_title': 'إضافة عنوان جديد',
    'edit_address_title': 'تعديل العنوان',
    'default_address': 'العنوان الافتراضي',
    'set_as_default': 'افتراضي',
    'no_addresses': 'لا توجد عناوين',
    'add_first_address': 'أضف عنوان التسليم الأول',
    'loading_addresses': 'جاري تحميل العناوين...',
    'delete_address': 'حذف العنوان',
    'confirm_delete_address': 'هل أنت متأكد من رغبتك في\nحذف هذا العنوان؟',
    'address_saved': 'تم حفظ العنوان بنجاح!',
    'address_updated': 'تم تحديث العنوان بنجاح!',
    'address_default_updated': 'تم تحديث عنوانك الافتراضي',
    'address_default_title': 'العنوان الافتراضي',
    'address_load_error': 'خطأ في تحميل العناوين',
    'new_badge': 'جديد!',
    'all_info_encrypted': 'جميع معلوماتك مشفرة',
    'info_encrypted_secure': 'معلوماتك مشفرة وآمنة',
    'update_address_info': 'قم بتحديث معلومات عنوانك',

    // ── نموذج العنوان ─────────────────────────────────────────────
    'section_contact_info': 'معلومات الاتصال',
    'section_address_info': 'معلومات العنوان',
    'contact_name': 'اسم جهة الاتصال',
    'contact_name_required': 'يرجى إدخال اسم جهة الاتصال',
    'hint_contact_name': 'مثال: أحمد بن علي',
    'phone': 'الهاتف',
    'phone_required': 'يرجى إدخال رقم الهاتف',
    'hint_phone': 'مثال: 20 123 456',
    'street': 'الشارع / العنوان',
    'street_required': 'يرجى إدخال العنوان',
    'hint_street': 'مثال: 12 شارع الحبيب بورقيبة',
    'complement': 'مكمّل العنوان',
    'hint_complement': 'مثال: شقة 4ب، مبنى ج',
    'province': 'المحافظة / الولاية',
    'province_required': 'يرجى إدخال المحافظة',
    'hint_province': 'مثال: تونس',
    'city': 'المدينة',
    'city_required': 'يرجى إدخال المدينة',
    'hint_city': 'مثال: تونس',
    'postal_code': 'الرمز البريدي',
    'postal_code_required': 'يرجى إدخال الرمز البريدي',
    'hint_postal_code': 'مثال: 1000',
    'country': 'البلد',
    'search_country': 'البحث عن بلد...',
    'save_address_btn': 'حفظ العنوان',
    'saving_address_btn': 'جاري الحفظ...',
    'update_address_btn': 'تحديث العنوان',
    'updating_address_btn': 'جاري التحديث...',
    'set_default_label': 'تعيين كعنوان افتراضي',
    'set_default_description': 'سيتم استخدام هذا العنوان تلقائياً في طلباتك',

    // ── مركز المساعدة ─────────────────────────────────────────────
    'help_center_title': 'مركز المساعدة',
    'help_search_hint': 'ابحث عن مساعدة...',
    'help_category_all': 'الكل',
    'help_empty_title': 'لم يتم العثور على نتائج',
    'help_empty_subtitle': 'حاول تعديل بحثك أو تغيير الفئة',
    'help_faq_content_unavailable': 'المحتوى غير متاح',
    'help_faq_load_error': 'خطأ في تحميل الأسئلة الشائعة',
    'help_support_fab': 'الدعم',
    'help_contact_title': 'التواصل مع الدعم',
    'help_chat_title': 'الدردشة المباشرة',
    'help_chat_subtitle': 'تحدث مع وكيل الآن',
    'help_chat_soon': 'الدردشة المباشرة قريباً!',
    'help_phone_title': 'الهاتف',
    'help_phone_subtitle': 'اتصل بنا على 000 000 70 216+',
    'help_phone_unavailable': 'تطبيق الهاتف غير متاح على هذا الجهاز',
    'help_email_title': 'البريد الإلكتروني',
    'help_email_subtitle': 'راسلنا على support@winzy.com',
    'help_email_copied': 'تم نسخ البريد الإلكتروني!',
    'help_email_fallback': 'البريد الإلكتروني: support@winzy.com',
    'help_category_commandes': 'الطلبات',
    'help_category_paiement': 'الدفع',
    'help_category_compte': 'الحساب',
    'help_category_livraison': 'التوصيل',
    'help_category_retours': 'المرتجعات',
    'help_category_securite': 'الأمان',
    'help_category_application': 'التطبيق',

    // ── إعدادات الإشعارات ─────────────────────────────────────────
    'notif_settings_title': 'إعدادات الإشعارات',
    'notif_save_tooltip': 'حفظ الإعدادات',
    'notif_saved_success': 'تم حفظ الإعدادات بنجاح!',
    'notif_section_general': 'الإشعارات العامة',
    'notif_push_title': 'إشعارات الدفع',
    'notif_push_subtitle': 'تلقي الإشعارات على جهازك',
    'notif_email_title': 'إشعارات البريد الإلكتروني',
    'notif_email_subtitle': 'تلقي الإشعارات عبر البريد الإلكتروني',
    'notif_section_orders': 'الطلبات والتوصيل',
    'notif_orders_title': 'تحديثات الطلب',
    'notif_orders_subtitle': 'تتبع طلبك وتوصيلك',
    'notif_section_marketing': 'التسويق والعروض',
    'notif_promo_title': 'العروض الترويجية',
    'notif_promo_subtitle': 'الخصومات والعروض الخاصة',
    'notif_new_products_title': 'منتجات جديدة',
    'notif_new_products_subtitle': 'اكتشف أحدث المنتجات',
    'notif_price_drops_title': 'انخفاض الأسعار',
    'notif_price_drops_subtitle': 'تنبيهات عند انخفاض الأسعار',
    'notif_newsletter_title': 'النشرة الإخبارية',
    'notif_newsletter_subtitle': 'أخبار ونصائح أسبوعية',
    'notif_section_account': 'الحساب والأمان',
    'notif_account_title': 'تحديثات الحساب',
    'notif_account_subtitle': 'تغييرات مهمة في حسابك',
    'notif_security_title': 'تنبيهات الأمان',
    'notif_security_subtitle': 'الأنشطة المشبوهة وتسجيلات الدخول',

    // ── طرق الدفع ─────────────────────────────────────────────────
    'payment_methods_title': 'طرق الدفع',
    'payment_manage_info': 'إدارة بطاقاتك وتفضيلات الدفع',
    'payment_add_fab': 'إضافة',
    'payment_security_title': 'أمان الدفع',
    'payment_security_desc': 'جميع معاملاتك مؤمّنة بتشفير SSL. لا يتم تخزين معلوماتك المصرفية على خوادمنا.',
    'payment_pci_certified': 'معتمد PCI DSS',
    'payment_set_default': 'تعيين كافتراضي',
    'payment_expires': 'تنتهي',
    'payment_add_sheet_title': 'إضافة طريقة دفع',
    'payment_card_option_title': 'بطاقة بنكية',
    'payment_card_option_subtitle': 'إضافة بطاقة Visa أو Mastercard جديدة...',
    'payment_cash_option_title': 'الدفع عند التسليم',
    'payment_cash_option_subtitle': 'تفعيل الدفع عند التسليم',
    'payment_cash_activated': 'تم تفعيل الدفع عند التسليم!',
    'payment_add_card_title': 'إضافة بطاقة بنكية',
    'payment_add_card_content': 'نموذج إضافة البطاقة سيتم تطبيقه مع خدمة الدفع.',
    'payment_edit_coming_soon': 'تعديل طريقة الدفع سيتم تطبيقه قريباً.',
    'payment_add_coming_soon': 'إضافة البطاقة سيتم تطبيقها قريباً.',
    'payment_delete_title': 'حذف طريقة الدفع',
    'payment_delete_confirm': 'هل أنت متأكد من رغبتك في حذف طريقة الدفع هذه؟',
    'payment_deleted_success': 'تم حذف طريقة الدفع',
    'payment_set_default_success': 'تم تعيين طريقة الدفع كافتراضية',
    'payment_cash_description': 'الدفع نقداً أو ببطاقة عند التسليم',

    // ── تعديل الملف الشخصي ────────────────────────────────────────
    'edit_profile_title': 'تعديل الملف الشخصي',
    'edit_profile_first_name': 'الاسم الأول',
    'edit_profile_hint_first_name': 'مثال: أحمد',
    'edit_profile_last_name': 'اللقب',
    'edit_profile_hint_last_name': 'مثال: بن علي',
    'edit_profile_email': 'البريد الإلكتروني',
    'edit_profile_email_readonly': 'لا يمكن تغيير البريد الإلكتروني لأسباب أمنية',
    'edit_profile_phone': 'الهاتف',
    'edit_profile_gender': 'الجنس',
    'edit_profile_saving': 'جاري الحفظ...',
    'edit_profile_save_btn': 'حفظ',
    'edit_profile_success': 'تم تحديث الملف الشخصي بنجاح!',
    'edit_profile_error': 'خطأ في تحديث الملف الشخصي',
    'edit_profile_notif_title': 'تم تحديث الملف الشخصي',
    'edit_profile_notif_body': 'تم حفظ معلوماتك بنجاح',
    'edit_profile_first_name_required': 'يرجى إدخال اسمك الأول',
    'edit_profile_last_name_required': 'يرجى إدخال لقبك',
    'edit_profile_phone_required': 'يرجى إدخال رقم هاتفك',
    'edit_profile_section_personal': 'المعلومات الشخصية',
    'edit_profile_section_contact': 'معلومات الاتصال',
  };

  // ── API ────────────────────────────────────────────────────────
  static String get(String key, {String? languageCode}) {
    final lang = languageCode ?? _currentLanguageCode;
    return _getTranslations(lang)[key] ?? key;
  }

  static Map<String, String> getAll({String? languageCode}) =>
      _getTranslations(languageCode ?? _currentLanguageCode);

  static Map<String, String> _getTranslations(String languageCode) {
    switch (languageCode) {
      case 'fr': return _fr;
      case 'en': return _en;
      case 'ar': return _ar;
      default:   return _fr;
    }
  }

  static String _currentLanguageCode = 'fr';
  static void setLanguage(String languageCode) => _currentLanguageCode = languageCode;
  static String getLanguage() => _currentLanguageCode;
  static bool get isRtl => _currentLanguageCode == 'ar';
}

extension AppStrings on String {
  String tr({String? languageCode}) =>
      AppLocalizations.get(this, languageCode: languageCode);
}