# Uncomment this line to define a global platform for your project
# platform :ios, '12.0'

# CocoaPods analytics sends network requests to Google Analytics
# To disable this, uncomment the following line
# ENV['COCOAPODS_DISABLE_STATS'] = 'true'

require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Flutter Pods
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  # Firebase Pods
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'GoogleSignIn', '~> 7.0.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
